// Mocks generated by Mockito 5.4.6 from annotations
// in my_web_app/test/pages/real_world_danshari_page_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i2;

import 'package:flutter/material.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:my_web_app/services/theme_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeColor_0 extends _i1.SmartFake implements _i2.Color {
  _FakeColor_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeThemeData_1 extends _i1.SmartFake implements _i3.ThemeData {
  _FakeThemeData_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [ThemeService].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeService extends _i1.Mock implements _i4.ThemeService {
  @override
  _i3.ThemeMode get themeMode => (super.noSuchMethod(
        Invocation.getter(#themeMode),
        returnValue: _i3.ThemeMode.system,
        returnValueForMissingStub: _i3.ThemeMode.system,
      ) as _i3.ThemeMode);

  @override
  bool get isDarkMode => (super.noSuchMethod(
        Invocation.getter(#isDarkMode),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i2.Color get primaryColor => (super.noSuchMethod(
        Invocation.getter(#primaryColor),
        returnValue: _FakeColor_0(
          this,
          Invocation.getter(#primaryColor),
        ),
        returnValueForMissingStub: _FakeColor_0(
          this,
          Invocation.getter(#primaryColor),
        ),
      ) as _i2.Color);

  @override
  String get selectedThemeCode => (super.noSuchMethod(
        Invocation.getter(#selectedThemeCode),
        returnValue: _i5.dummyValue<String>(
          this,
          Invocation.getter(#selectedThemeCode),
        ),
        returnValueForMissingStub: _i5.dummyValue<String>(
          this,
          Invocation.getter(#selectedThemeCode),
        ),
      ) as String);

  @override
  bool get hasListeners => (super.noSuchMethod(
        Invocation.getter(#hasListeners),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.ThemeMode getFlutterThemeMode() => (super.noSuchMethod(
        Invocation.method(
          #getFlutterThemeMode,
          [],
        ),
        returnValue: _i3.ThemeMode.system,
        returnValueForMissingStub: _i3.ThemeMode.system,
      ) as _i3.ThemeMode);

  @override
  void toggleTheme() => super.noSuchMethod(
        Invocation.method(
          #toggleTheme,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setThemeMode(_i3.ThemeMode? mode) => super.noSuchMethod(
        Invocation.method(
          #setThemeMode,
          [mode],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void setPrimaryColor(_i2.Color? color) => super.noSuchMethod(
        Invocation.method(
          #setPrimaryColor,
          [color],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<void> applyThemeByCode(String? code) => (super.noSuchMethod(
        Invocation.method(
          #applyThemeByCode,
          [code],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i3.ThemeData getLightTheme() => (super.noSuchMethod(
        Invocation.method(
          #getLightTheme,
          [],
        ),
        returnValue: _FakeThemeData_1(
          this,
          Invocation.method(
            #getLightTheme,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeThemeData_1(
          this,
          Invocation.method(
            #getLightTheme,
            [],
          ),
        ),
      ) as _i3.ThemeData);

  @override
  _i3.ThemeData getDarkTheme() => (super.noSuchMethod(
        Invocation.method(
          #getDarkTheme,
          [],
        ),
        returnValue: _FakeThemeData_1(
          this,
          Invocation.method(
            #getDarkTheme,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeThemeData_1(
          this,
          Invocation.method(
            #getDarkTheme,
            [],
          ),
        ),
      ) as _i3.ThemeData);

  @override
  void addListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #addListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void removeListener(_i2.VoidCallback? listener) => super.noSuchMethod(
        Invocation.method(
          #removeListener,
          [listener],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void notifyListeners() => super.noSuchMethod(
        Invocation.method(
          #notifyListeners,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
