#!/usr/bin/env python3
"""
competitor_report_gen.py - Generate weekly competitor discovery markdown report.
Usage: python3 competitor_report_gen.py <today> <week> <total> <staged> <skipped> <existing> <output_path>
Called by competitor-discovery.yml Step 4.
"""
import json
import sys
from collections import Counter

today, week, total, staged, skipped, existing, output_path = sys.argv[1:8]

with open("/tmp/all_candidates.json") as f:
    data = json.load(f)

cats = Counter(c.get("category", "unknown") for c in data)
cats_md = (
    "\n".join(f"- **{cat}**: {n} 社" for cat, n in sorted(cats.items()))
    or "- (データなし)"
)

lines = []
for c in data[:20]:
    name = c.get("display_name", c.get("id", "?"))
    cat = c.get("category", "?")
    score = c.get("ai_score", 0)
    threat = c.get("threat_level", "?")
    website = c.get("website", "")
    desc = (c.get("description") or "")[:100]
    reason = c.get("reason_trending", "")
    lines += [
        f"### {name} ({cat})",
        f"- **サイト**: {website}",
        f"- **脅威レベル**: {threat} / AI Score: {score}",
        f"- **概要**: {desc}",
    ]
    if reason:
        lines.append(f"- **トレンド理由**: {reason}")
    lines.append("")
candidates_md = "\n".join(lines) if lines else "(候補なし)"

report = "\n".join([
    f"# 競合候補発掘レポート — {today} (Week {week})",
    "",
    f"**既存競合数**: {existing} 社",
    f"**Gemini 発掘候補**: {total} 社",
    f"**新規 staging**: {staged} 社",
    f"**重複スキップ**: {skipped} 社",
    "",
    "## 発掘カテゴリ",
    "",
    cats_md,
    "",
    "## 新規候補 (PS#4 review 待ち)",
    "",
    candidates_md,
    "## 次のアクション",
    "",
    "1. `competitor_candidates` テーブルを確認 (reviewed=false の候補)",
    "2. 採用判断 → seed migration 作成 → competitors に promote",
    "3. 拒否 → rejected_reason 記入 + reviewed=true",
    "",
    "```sql",
    "-- 未レビュー候補一覧",
    "SELECT id, display_name, category, ai_score, threat_level, staged_at",
    "FROM competitor_candidates",
    "WHERE reviewed = false AND promoted = false",
    "ORDER BY ai_score DESC NULLS LAST, staged_at DESC;",
    "```",
    "",
    "---",
    f"*Generated by competitor-discovery.yml — Week {week}*",
])

with open(output_path, "w", encoding="utf-8") as f:
    f.write(report)
print(f"Report written: {output_path}")
