// GENERATED FILE. DO NOT EDIT.
// Generated by scripts/update_kokumin_local_endorsements.py.
library;

import '../models/election_intelligence.dart';

const String dpjOfficialEndorsementSourceUrl =
    'https://new-kokumin.jp/local-election-list';
const String dpjOfficialEndorsementSourceAsOf = '2026-08-31';
const String dpjOfficialEndorsementSourceDocumentSha256 =
    'd0c45eac70b1cd84837b5794413ef20d0a30cefba7dade45811c2ff204332174';
const int dpjOfficialRecommendationEntryCount = 7;

const List<OfficialEndorsementPrefecture> dpjOfficialEndorsements =
    <OfficialEndorsementPrefecture>[
  OfficialEndorsementPrefecture(
    prefecture: '北海道',
    totalCount: 6,
    incumbentCount: 2,
    newcomerCount: 4,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '青森',
    totalCount: 5,
    incumbentCount: 2,
    newcomerCount: 2,
    formerCount: 1,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '秋田',
    totalCount: 3,
    incumbentCount: 1,
    newcomerCount: 2,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '福島',
    totalCount: 1,
    incumbentCount: 0,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '茨城',
    totalCount: 6,
    incumbentCount: 5,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '栃木',
    totalCount: 1,
    incumbentCount: 1,
    newcomerCount: 0,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '群馬',
    totalCount: 3,
    incumbentCount: 2,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '埼玉',
    totalCount: 5,
    incumbentCount: 2,
    newcomerCount: 2,
    formerCount: 1,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '千葉',
    totalCount: 21,
    incumbentCount: 2,
    newcomerCount: 17,
    formerCount: 2,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '東京',
    totalCount: 36,
    incumbentCount: 29,
    newcomerCount: 5,
    formerCount: 2,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '神奈川',
    totalCount: 39,
    incumbentCount: 11,
    newcomerCount: 28,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '新潟',
    totalCount: 2,
    incumbentCount: 0,
    newcomerCount: 2,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '石川',
    totalCount: 2,
    incumbentCount: 1,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '長野',
    totalCount: 2,
    incumbentCount: 0,
    newcomerCount: 2,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '岐阜',
    totalCount: 9,
    incumbentCount: 2,
    newcomerCount: 7,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '静岡',
    totalCount: 11,
    incumbentCount: 7,
    newcomerCount: 4,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '愛知',
    totalCount: 25,
    incumbentCount: 18,
    newcomerCount: 7,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '京都',
    totalCount: 10,
    incumbentCount: 8,
    newcomerCount: 2,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '大阪',
    totalCount: 10,
    incumbentCount: 7,
    newcomerCount: 3,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '兵庫',
    totalCount: 1,
    incumbentCount: 1,
    newcomerCount: 0,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '奈良',
    totalCount: 1,
    incumbentCount: 0,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '和歌山',
    totalCount: 1,
    incumbentCount: 0,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '鳥取',
    totalCount: 1,
    incumbentCount: 0,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '岡山',
    totalCount: 4,
    incumbentCount: 2,
    newcomerCount: 2,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '広島',
    totalCount: 3,
    incumbentCount: 1,
    newcomerCount: 2,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '山口',
    totalCount: 2,
    incumbentCount: 1,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '香川',
    totalCount: 1,
    incumbentCount: 0,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '愛媛',
    totalCount: 4,
    incumbentCount: 2,
    newcomerCount: 1,
    formerCount: 1,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '高知',
    totalCount: 2,
    incumbentCount: 0,
    newcomerCount: 1,
    formerCount: 1,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '福岡',
    totalCount: 15,
    incumbentCount: 2,
    newcomerCount: 13,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '佐賀',
    totalCount: 1,
    incumbentCount: 0,
    newcomerCount: 1,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '長崎',
    totalCount: 7,
    incumbentCount: 3,
    newcomerCount: 4,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '熊本',
    totalCount: 5,
    incumbentCount: 0,
    newcomerCount: 5,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '大分',
    totalCount: 1,
    incumbentCount: 1,
    newcomerCount: 0,
    formerCount: 0,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '宮崎',
    totalCount: 14,
    incumbentCount: 0,
    newcomerCount: 13,
    formerCount: 1,
  ),
  OfficialEndorsementPrefecture(
    prefecture: '沖縄',
    totalCount: 4,
    incumbentCount: 1,
    newcomerCount: 2,
    formerCount: 1,
  ),
];

const int dpjOfficialEndorsementTotal = 264;
const int dpjOfficialEndorsementIncumbentTotal = 114;
const int dpjOfficialEndorsementNewcomerTotal = 140;
const int dpjOfficialEndorsementFormerTotal = 10;
const int dpjOfficialEndorsementPrefectureCount = 36;

OfficialEndorsementPrefecture? dpjOfficialEndorsementFor(
  String prefecture,
) {
  final normalized = prefecture.replaceFirst(
    RegExp(r'[都府県]$'),
    '',
  );
  for (final item in dpjOfficialEndorsements) {
    if (item.prefecture == normalized) {
      return item;
    }
  }
  return null;
}
