import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

export const root = fileURLToPath(new URL('../../', import.meta.url));
export const sourcePath = 'web/labs/shared/download-json.mjs';
export const outputPath = 'web/labs/shared/reference.html';
const escape = (text) => String(text).replace(/[&<>"']/g, (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);

export function parseDoclets(source = path.join(root, sourcePath)) {
  // JSDoc parses source only; never import/execute the target module here.
  return JSON.parse(execFileSync(process.execPath, [
    fileURLToPath(new URL('node_modules/jsdoc/jsdoc.js', import.meta.url)),
    '-X', '--pedantic', '-c', fileURLToPath(new URL('jsdoc.json', import.meta.url)), source,
  ], { encoding: 'utf8', maxBuffer: 4 * 1024 * 1024 }));
}

export function documentedFunction(doclets) {
  const matches = doclets.filter((d) => d.kind === 'function' && d.name === 'downloadJson');
  if (matches.length !== 1) throw new Error('Expected exactly one downloadJson function');
  const doc = matches[0];
  const params = doc.params || [];
  if (!doc.description?.trim() || doc.undocumented || !doc.examples?.length ||
      !doc.returns?.[0]?.description?.trim() || !doc.exceptions?.[0]?.description?.trim()) {
    throw new Error('Missing description, example, return or exception documentation');
  }
  const actualParams = doc.meta?.code?.paramnames;
  if (!actualParams || JSON.stringify(params.map((p) => p.name)) !== JSON.stringify(actualParams) ||
      params.some((p) => !p.description?.trim() || !p.type?.names?.length)) {
    throw new Error('Parameter documentation does not match source signature');
  }
  return doc;
}

export function renderReference(doclets, source) {
  const doc = documentedFunction(doclets);
  const hash = createHash('sha256').update(source.replace(/\r\n/g, '\n')).digest('hex');
  const type = (item) => escape((item.type?.names || []).join(' | '));
  const section = (id, title, content) => `<section id="${id}"><h2>${title}</h2>${content}</section>`;
  return `<!doctype html>
<!-- Generated by scripts/api-docs/generate.mjs. Edit JSDoc, not this file. -->
<html lang="ja"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>JSON保存 APIリファレンス | 自分株式会社</title>
<meta name="description" content="共通JSON保存ヘルパーの引数、例外、使用例。ソースのJSDocから生成。">
<style>
:root{color-scheme:light;font-family:system-ui,sans-serif;color:#182a3a;background:#f4f7fb}*{box-sizing:border-box}body{margin:0}main{max-width:880px;margin:auto;padding:40px 24px 72px}a{color:#164a99;text-underline-offset:3px}a:focus-visible{outline:3px solid #164a99;outline-offset:4px}header{border-bottom:1px solid #b7c6d8;padding-bottom:24px}h1{font-size:clamp(1.8rem,5vw,2.7rem);line-height:1.25;margin:12px 0}h2{font-size:1.3rem}h3{font-size:1.1rem}p,dd{line-height:1.8}nav{display:flex;flex-wrap:wrap;gap:16px;margin:24px 0}section{background:white;border:1px solid #d4deea;border-radius:12px;padding:24px;margin:20px 0;scroll-margin-top:20px}dt{font-weight:700;margin-top:16px}dd{margin:4px 0 16px}pre{background:#edf2f8;padding:16px;white-space:pre-wrap;overflow-wrap:anywhere;line-height:1.7}code{font-family:ui-monospace,monospace;overflow-wrap:anywhere}.description{white-space:pre-line}.meta{font-size:.85rem;overflow-wrap:anywhere}footer{line-height:1.8}@media(max-width:480px){main{padding:24px 16px 48px}section{padding:18px}}
</style></head><body><main>
<header><a href="/">自分株式会社</a><p>開発者向け / ブラウザー共通モジュール</p><h1>JSON保存 APIリファレンス</h1><p><code>downloadJson(${doc.params.map((p) => escape(p.name)).join(', ')})</code></p><p>ソースのJSDocから生成した参照文書です。</p></header>
<nav aria-label="ページ内目次"><a href="#usage">概要と制約</a><a href="#parameters">引数</a><a href="#errors">戻り値と例外</a><a href="#examples">使用例</a><a href="#maintenance">修正方法</a></nav>
${section('usage', '概要と制約', `<p class="description">${escape(doc.description)}</p>`)}
${section('parameters', '引数', `<dl>${doc.params.map((p) => `<dt><code>${escape(p.name)}</code> : <code>${type(p)}</code></dt><dd>${escape(p.description)}</dd>`).join('')}</dl>`)}
${section('errors', '戻り値と例外', `<h3>戻り値</h3>${doc.returns.map((p) => `<p><code>${type(p)}</code> — ${escape(p.description)}</p>`).join('')}<h3>例外</h3>${doc.exceptions.map((p) => `<p><code>${type(p)}</code> — ${escape(p.description)}</p>`).join('')}`)}
${section('examples', '使用例', doc.examples.map((example) => `<pre><code>${escape(example)}</code></pre>`).join(''))}
${section('maintenance', '修正方法', `<p>説明の誤りは<a href="https://github.com/kanta13jp1/my_web_app/blob/main/${sourcePath}">元のJSDocを修正</a>してください。生成HTMLを直接編集せず、手順に従って再生成します。</p><p><a href="https://github.com/kanta13jp1/my_web_app/blob/main/docs/LAB_API_REFERENCE.md">文書更新ガイドと設計上の判断</a></p><pre><code>npm ci --prefix scripts/api-docs --ignore-scripts
node scripts/api-docs/generate.mjs --write
node --test scripts/api-docs/reference.test.mjs
node scripts/api-docs/generate.mjs --check</code></pre>`)}
<footer><p class="meta">対象ソース: <code>${sourcePath}</code><br>ソース SHA-256: <code>${hash}</code><br>生成器: JSDoc 4.0.5 / 対象はこのモジュールのみ</p><p>生成の一致は、説明の意味やすべてのブラウザーでの動作を保証しません。</p></footer>
</main></body></html>
`;
}

export function checkOutput(actual, expected) {
  if (actual.replace(/\r\n/g, '\n') !== expected) {
    throw new Error('Stale API reference. Run node scripts/api-docs/generate.mjs --write');
  }
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const mode = process.argv[2];
  if (!['--write', '--check'].includes(mode)) throw new Error('Use --write or --check');
  const generated = renderReference(parseDoclets(), readFileSync(path.join(root, sourcePath), 'utf8'));
  if (mode === '--write') writeFileSync(path.join(root, outputPath), generated);
  else checkOutput(readFileSync(path.join(root, outputPath), 'utf8'), generated);
  console.log(`${mode}: ${outputPath}`);
}
