"""Add provenance watermark + metadata to AI-generated videos.

Implements docs/AI_VIDEO_PRINCIPLES.md principle #5 (Ethical Provenance &
Transparency) — the visible watermark + embedded metadata layers of the
3-layer transparency model. The third layer (UI badge in
philosophy_page.dart) is implemented separately in lib/pages.

Standalone — only depends on ffmpeg being on PATH and the input mp4
existing. Output mp4 is re-encoded once with drawtext overlay and
metadata fields populated.

Usage:
    python scripts/video/add_provenance.py \\
        --input videos/output_D.mp4 \\
        --output videos/output_D_provenanced.mp4 \\
        --title "Cartesia AI 解説" \\
        --series-number 12 \\
        --source-sha256 <hex> \\
        --model "NotebookLM Deep Research + Claude Code Win版"

Exit codes:
    0  success
    1  ffmpeg failure
    2  invalid arguments
"""

from __future__ import annotations

import argparse
import hashlib
import shlex
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

WATERMARK_TEXT = "自分株式会社 AI 生成"
WATERMARK_FONT = "Noto Sans CJK JP"


def build_drawtext_filter(text: str, font: str) -> str:
    escaped = text.replace(":", r"\:").replace("'", r"\'")
    return (
        f"drawtext="
        f"text='{escaped}':"
        f"font='{font}':"
        f"fontsize=18:"
        f"fontcolor=white@0.85:"
        f"box=1:boxcolor=black@0.5:boxborderw=8:"
        f"x=w-tw-20:y=h-th-20"
    )


def sha256_of_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as fp:
        for chunk in iter(lambda: fp.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def build_ffmpeg_cmd(
    input_path: Path,
    output_path: Path,
    title: str,
    series_number: int,
    source_sha256: str,
    model: str,
    creation_time: str,
) -> list[str]:
    drawtext = build_drawtext_filter(WATERMARK_TEXT, WATERMARK_FONT)
    comment = (
        f"AI-generated by 自分株式会社 / series #{series_number} / "
        f"source SHA-256: {source_sha256} / model: {model}"
    )
    return [
        "ffmpeg",
        "-y",
        "-i",
        str(input_path),
        "-vf",
        drawtext,
        "-c:v",
        "libx264",
        "-preset",
        "fast",
        "-crf",
        "22",
        "-c:a",
        "copy",
        "-metadata",
        f"title={title}",
        "-metadata",
        f"comment={comment}",
        "-metadata",
        f"creation_time={creation_time}",
        "-metadata",
        "artist=自分株式会社 AI",
        "-metadata",
        "encoder=jibun-kabushiki-gaisha-ai-video-pipeline",
        str(output_path),
    ]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--input", required=True, type=Path, help="Input mp4 path")
    parser.add_argument("--output", required=True, type=Path, help="Output mp4 path")
    parser.add_argument("--title", required=True, type=str, help="Video title (used as -metadata title)")
    parser.add_argument("--series-number", required=True, type=int, help="AI 大学 series number")
    parser.add_argument(
        "--source-sha256",
        required=False,
        type=str,
        default=None,
        help="SHA-256 of source text (for tamper detection); auto-computed from --source-file if omitted",
    )
    parser.add_argument(
        "--source-file",
        required=False,
        type=Path,
        default=None,
        help="Path to source text file; SHA-256 will be computed if --source-sha256 not given",
    )
    parser.add_argument(
        "--model",
        required=False,
        type=str,
        default="NotebookLM Deep Research + Claude Code",
        help="Model name (for -metadata comment)",
    )
    parser.add_argument(
        "--print-cmd-only",
        action="store_true",
        help="Print the ffmpeg cmd without executing (for tests)",
    )
    args = parser.parse_args(argv)

    if not args.print_cmd_only and not args.input.exists():
        print(f"[FAIL] Input mp4 not found: {args.input}", file=sys.stderr)
        return 2

    source_sha256 = args.source_sha256
    if source_sha256 is None:
        if args.source_file is None or not args.source_file.exists():
            print(
                "[FAIL] Either --source-sha256 or an existing --source-file is required",
                file=sys.stderr,
            )
            return 2
        source_sha256 = sha256_of_file(args.source_file)

    creation_time = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000000Z")

    cmd = build_ffmpeg_cmd(
        input_path=args.input,
        output_path=args.output,
        title=args.title,
        series_number=args.series_number,
        source_sha256=source_sha256,
        model=args.model,
        creation_time=creation_time,
    )

    if args.print_cmd_only:
        print(" ".join(shlex.quote(c) for c in cmd))
        return 0

    print(f"[INFO] Running: {' '.join(shlex.quote(c) for c in cmd[:6])} ...")
    try:
        proc = subprocess.run(cmd, check=False, capture_output=True, text=True)
    except FileNotFoundError:
        print("[FAIL] ffmpeg not found on PATH", file=sys.stderr)
        return 1

    if proc.returncode != 0:
        sys.stderr.write(proc.stderr)
        print(f"[FAIL] ffmpeg exited {proc.returncode}", file=sys.stderr)
        return 1

    print(f"[PASS] Provenance applied: {args.output}")
    print(f"  source SHA-256: {source_sha256}")
    print(f"  creation_time:  {creation_time}")
    print(f"  watermark:      {WATERMARK_TEXT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
