import 'dart:convert';
import 'handoff_bundle.dart';

class FlutterCodegen {
  static const _outputDir = 'lib/widgets/generated/claude_design';

  static String generateFromComponent(DesignComponent component) {
    final className = _toPascalCase(component.name);
    final widgetBody = _generateFromHtml(component.htmlSnippet);
    return _wrapWidget(className, widgetBody);
  }

  static String generateFromComponents(List<DesignComponent> components) {
    if (components.isEmpty) {
      return '// No components to generate';
    }
    final parts = components.map(generateFromComponent);
    return parts.join('\n\n');
  }

  // Generates a single widget string from HTML snippet (pattern-based, ~70% fidelity)
  static String _generateFromHtml(String html) {
    if (html.trim().isEmpty) return 'const SizedBox.shrink()';

    final trimmed = html.trim();

    // Button patterns
    if (_matchesTag(trimmed, 'button')) {
      final text = _extractInnerText(trimmed);
      final isOutlined =
          trimmed.contains('outlined') || trimmed.contains('border:');
      if (isOutlined) {
        return "OutlinedButton(\n  onPressed: () {},\n  child: Text('$text'),\n)";
      }
      return "ElevatedButton(\n  onPressed: () {},\n  child: Text('$text'),\n)";
    }

    // Input patterns
    if (_matchesTag(trimmed, 'input') || _matchesTag(trimmed, 'textarea')) {
      final placeholder = _extractAttr(trimmed, 'placeholder') ?? 'Enter text';
      return "TextField(\n  decoration: InputDecoration(\n    hintText: '$placeholder',\n  ),\n)";
    }

    // Image patterns
    if (_matchesTag(trimmed, 'img')) {
      final src = _extractAttr(trimmed, 'src') ?? '';
      final alt = _extractAttr(trimmed, 'alt') ?? '';
      return src.isEmpty
          ? 'const Icon(Icons.image_outlined)'
          : "Image.network('$src', semanticLabel: '$alt')";
    }

    // Heading patterns
    for (final level in ['h1', 'h2', 'h3']) {
      if (_matchesTag(trimmed, level)) {
        final text = _extractInnerText(trimmed);
        final style = _headingStyle(level);
        return "Text(\n  '$text',\n  style: $style,\n)";
      }
    }

    // Paragraph / span patterns
    if (_matchesTag(trimmed, 'p') || _matchesTag(trimmed, 'span')) {
      final text = _extractInnerText(trimmed);
      return "Text('$text')";
    }

    // Flex row/column patterns
    if (_matchesTag(trimmed, 'div')) {
      final style = _extractAttr(trimmed, 'style') ?? '';
      final isRow = style.contains('flex-direction: row') ||
          style.contains('flex-direction:row') ||
          (style.contains('display: flex') && !style.contains('column'));
      final padding = _extractPadding(style);
      final children = _extractChildren(trimmed);

      final axis = isRow ? 'Row' : 'Column';
      final paddingWrap =
          padding != null ? 'Padding(\n  padding: $padding,\n  child: ' : '';
      final paddingClose = padding != null ? ',\n)' : '';

      if (children.isEmpty) {
        final inner = 'const $axis(children: [])';
        return '$paddingWrap$inner$paddingClose';
      }

      final childWidgets =
          children.map((c) => '    ${_generateFromHtml(c)},').join('\n');
      final inner = '$axis(\n  children: [\n$childWidgets\n  ],\n)';
      return '$paddingWrap$inner$paddingClose';
    }

    // Fallback: wrap raw content in a Text
    final text = _stripTags(trimmed).trim();
    return text.isNotEmpty
        ? "Text('${_escapeString(text)}')"
        : 'const SizedBox.shrink()';
  }

  static String _wrapWidget(String className, String body) {
    final indented = body.split('\n').map((l) => '      $l').join('\n');
    return '''
// Generated by Claude Design Importer — review before using in production
// Output: $_outputDir/${_toSnakeCase(className)}.dart
import 'package:flutter/material.dart';

class $className extends StatelessWidget {
  const $className({super.key});

  @override
  Widget build(BuildContext context) {
    return $indented;
  }
}
''';
  }

  // ─── HTML helpers ────────────────────────────────────────────────────────

  static bool _matchesTag(String html, String tag) {
    return html.toLowerCase().startsWith('<$tag') ||
        html.toLowerCase().startsWith('<$tag ');
  }

  static String? _extractAttr(String html, String attr) {
    final re = RegExp('$attr=["\']([^"\']*)["\']', caseSensitive: false);
    return re.firstMatch(html)?.group(1);
  }

  static String _extractInnerText(String html) {
    final stripped = _stripTags(html).trim();
    return _escapeString(stripped.isEmpty ? '' : stripped);
  }

  static String _stripTags(String html) {
    return html.replaceAll(RegExp(r'<[^>]+>'), '');
  }

  static String _escapeString(String s) {
    return s.replaceAll("'", "\\'").replaceAll('\n', ' ').trim();
  }

  static String? _extractPadding(String style) {
    final re = RegExp(r'padding:\s*([\d.]+)px', caseSensitive: false);
    final m = re.firstMatch(style);
    if (m == null) return null;
    final px = double.tryParse(m.group(1) ?? '') ?? 0;
    return 'EdgeInsets.all($px)';
  }

  // Naive children extraction: splits on top-level tags
  static List<String> _extractChildren(String html) {
    final innerRe = RegExp(r'^<[^>]+>(.*)</[^>]+>$', dotAll: true);
    final inner = innerRe.firstMatch(html)?.group(1)?.trim() ?? '';
    if (inner.isEmpty) return [];

    final children = <String>[];
    var depth = 0;
    var start = 0;
    for (var i = 0; i < inner.length; i++) {
      if (inner[i] == '<') {
        if (i + 1 < inner.length && inner[i + 1] == '/') {
          depth--;
          if (depth == 0) {
            final end = inner.indexOf('>', i) + 1;
            children.add(inner.substring(start, end).trim());
            start = end;
          }
        } else if (!inner.substring(i).startsWith('<!')) {
          if (depth == 0) start = i;
          depth++;
        }
      }
    }
    return children.where((c) => c.isNotEmpty).toList();
  }

  static String _headingStyle(String level) {
    switch (level) {
      case 'h1':
        return 'const TextStyle(fontSize: 28, fontWeight: FontWeight.w700, color: Color(0xFFE2E8F0))';
      case 'h2':
        return 'const TextStyle(fontSize: 22, fontWeight: FontWeight.w600, color: Color(0xFFE2E8F0))';
      default:
        return 'const TextStyle(fontSize: 18, fontWeight: FontWeight.w600, color: Color(0xFFE2E8F0))';
    }
  }

  // ─── String utils ────────────────────────────────────────────────────────

  static String _toPascalCase(String s) {
    return s.split(RegExp(r'[\s_-]+')).map((w) {
      if (w.isEmpty) return '';
      return w[0].toUpperCase() + w.substring(1);
    }).join();
  }

  static String _toSnakeCase(String s) {
    return s
        .replaceAllMapped(
          RegExp(r'[A-Z]'),
          (m) => '_${m.group(0)!.toLowerCase()}',
        )
        .replaceAll(RegExp(r'^_'), '');
  }

  // ─── JSON export ─────────────────────────────────────────────────────────

  static Map<String, dynamic> generationReport(
    List<DesignComponent> components,
  ) {
    return {
      'count': components.length,
      'outputDir': _outputDir,
      'generatedAt': DateTime.now().toIso8601String(),
      'components': components
          .map(
            (c) => {
              'name': c.name,
              'code': generateFromComponent(c),
            },
          )
          .toList(),
    };
  }

  static String reportAsJson(List<DesignComponent> components) {
    const encoder = JsonEncoder.withIndent('  ');
    return encoder.convert(generationReport(components));
  }
}
