const String _shareTitle = '【自分株式会社 経営戦略】';
const String _shareLead = '今日のやるべきことをAIと運営導線で1件に絞る。';
const String _shareLeadSub = '「自分株式会社」を使って人生を経営中。';
const String _shareCta = '今すぐ試す → https://my-web-app-b67f4.web.app/';
const String _shareFooter = '(Generated by MAGI System)\n#自分株式会社';

String buildAiSecretaryPrompt({
  required String strategyLabel,
  required List<Map<String, dynamic>> recentNotesJson,
}) {
  final notesSummary = recentNotesJson.isEmpty
      ? '最新のノートはありません。'
      : recentNotesJson.take(8).map((note) {
          final title = (note['title'] ?? '無題').toString().trim();
          final content = (note['content'] ?? '').toString().trim();
          final normalizedContent = content.replaceAll(RegExp(r'\s+'), ' ');
          final excerpt = normalizedContent.length > 90
              ? '${normalizedContent.substring(0, 90)}...'
              : normalizedContent;
          return '- $title: $excerpt';
        }).join('\n');

  return '''
あなたは「自分株式会社」のMAGI戦略秘書です。ユーザーの最新ノートを踏まえて、「$strategyLabel」の戦略文を日本語で提案してください。
出力ルール:
- Markdownで返す
- 挨拶文は禁止。すぐ本題に入る
- 必ず4つの見出しをこの順番で使う
  ## 最優先でやること
  ## 理由
  ## 48時間以内にやること
  ## やらないこと
- 箇条書きは各見出しの配下にだけ書く
- 「最優先でやること」は必ず1項目だけにする
- 「最優先でやること」は、読んだ瞬間に着手できる具体性にする。曖昧な精神論は禁止
- 「48時間以内にやること」は必ず2項目にする
- 「やらないこと」は、上の行動を守るためのノイズ遮断にする
- 固有名詞は、本文中の具体的な書名・人物名・資料名から必ず選ぶ
- 最新ノートに固有名詞候補（例: 直近のタイトル、テーマ候補、読書中の書籍名）があれば、その固有名詞を優先して使う
- 文面全体は、見た人が「ここまで次の一手が明確なら、このアプリを使いたい」と感じるレベルまで、優先順位が明確で、迷いが減る書き方にする
- アプリ名、URL、外部文、(Generated by MAGI System)、ダウンロード表記、ハッシュタグは本文に含めない
最新のノート:
$notesSummary
''';
}

String buildAiSecretaryShareText(String strategyResult) {
  final sanitizedLines = strategyResult.split('\n').where((line) {
    final trimmed = line.trim();
    if (trimmed.isEmpty) return true;
    if (trimmed == _shareTitle) return false;
    if (trimmed == _shareLead) return false;
    if (trimmed == _shareLeadSub) return false;
    if (trimmed == _shareCta) return false;
    if (trimmed == '(Generated by MAGI System)') return false;
    if (trimmed.startsWith('ダウンロード:')) return false;
    if (trimmed.startsWith('今すぐ試す →')) return false;
    if (trimmed == '#自分株式会社') return false;
    return true;
  }).toList();

  final sanitizedBody = sanitizedLines.join('\n').trim();
  final body = sanitizedBody.isEmpty ? '生成結果がありません。' : sanitizedBody;

  return '$_shareTitle\n\n$_shareLead\n$_shareLeadSub\n\n$body\n\n$_shareCta\n\n$_shareFooter';
}
