const String _shareTitle = '【自分株式会社 経営戦略】';
const String _shareFooter =
    '(Generated by MAGI System)\nダウンロード: https://my-web-app-b67f4.web.app/\n#自分株式会社';

String buildAiSecretaryPrompt({
  required String strategyLabel,
  required List<Map<String, dynamic>> recentNotesJson,
}) {
  final notesSummary = recentNotesJson.isEmpty
      ? '最近のノートはありません。'
      : recentNotesJson.take(8).map((note) {
          final title = (note['title'] ?? '無題').toString().trim();
          final content = (note['content'] ?? '').toString().trim();
          final normalizedContent = content.replaceAll(RegExp(r'\s+'), ' ');
          final excerpt = normalizedContent.length > 90
              ? '${normalizedContent.substring(0, 90)}...'
              : normalizedContent;
          return '- $title: $excerpt';
        }).join('\n');

  return '''
あなたは「自分株式会社」のMAGI戦略秘書です。
ユーザーの最近のノートを踏まえて、$strategyLabelの行動計画を日本語で提案してください。

出力条件:
- Markdownで返す
- 抽象論ではなく、すぐ動ける具体策にする
- 以下の4項目を、この順番・この見出しで必ず含める
  ## 最優先でやること
  ## 理由
  ## 48時間以内にやること
  ## やらないこと
- 各見出しの直下は箇条書きのみ。番号付きリストは使わない
- 「最優先でやること」「48時間以内にやること」「やらないこと」の箇条書きは、行動部分を **太字** で始める
- 「48時間以内にやること」は2項目にする
- 最近のノートに固有名詞（本のタイトル、テーマ名、進行中の案件）があれば、その固有名詞を優先して使う
- アプリ名、URL、署名、(Generated by MAGI System)、ダウンロード表記、ハッシュタグは本文に含めない

最近のノート:
$notesSummary
''';
}

String buildAiSecretaryShareText(String strategyResult) {
  final sanitizedLines = strategyResult.split('\n').where((line) {
    final trimmed = line.trim();
    if (trimmed.isEmpty) return true;
    if (trimmed == _shareTitle) return false;
    if (trimmed == '(Generated by MAGI System)') return false;
    if (trimmed.startsWith('ダウンロード:')) return false;
    if (trimmed == '#自分株式会社') return false;
    return true;
  }).toList();

  final sanitizedBody = sanitizedLines.join('\n').trim();
  final body = sanitizedBody.isEmpty ? '（本文なし）' : sanitizedBody;

  return '$_shareTitle\n\n$body\n\n$_shareFooter';
}
