const String _shareTitle = '【自分株式会社 経営戦略】';
const String _shareLead = '迷いを減らして、次の一手まで一気に整理。';
const String _shareLeadSub = 'このアプリなら、最優先・理由・48時間以内の行動がすぐ決まります。';
const String _shareFooter =
    '(Generated by MAGI System)\nダウンロード: https://my-web-app-b67f4.web.app/\n#自分株式会社';

String buildAiSecretaryPrompt({
  required String strategyLabel,
  required List<Map<String, dynamic>> recentNotesJson,
}) {
  final notesSummary = recentNotesJson.isEmpty
      ? '最新のノートはありません。'
      : recentNotesJson.take(8).map((note) {
          final title = (note['title'] ?? '無題').toString().trim();
          final content = (note['content'] ?? '').toString().trim();
          final normalizedContent = content.replaceAll(RegExp(r'\s+'), ' ');
          final excerpt = normalizedContent.length > 90
              ? '${normalizedContent.substring(0, 90)}...'
              : normalizedContent;
          return '- $title: $excerpt';
        }).join('\n');

  return '''
あなたは「自分株式会社」のMAGI戦略秘書です。ユーザーの最新ノートを踏まえて、「$strategyLabel」の経営戦略文を日本語で提案してください。
出力ルール:
- Markdownで返す
- 挨拶文は禁止、すぐ本題に入る
- 必ず4見出しで、この順番で書く
  ## 最優先でやること
  ## 理由
  ## 48時間以内にやること
  ## やらないこと
- 箇条書きは各見出しの配下にだけ書く
- 固有名詞は、本文中の具体的な書名・人物名・資料名から必ず選ぶ
- 「最優先でやること」は「48時間以内にやること」より重要で、太字で始める
- 「48時間以内にやること」は必ず2項目にする
- 読み手が「このアプリなら次の一手がすぐ決まる」と感じるように、文面全体を「迷いが減る」「すぐ着手できる」「後で見返しやすい」印象で書く。アプリ名を本文に直接書く必要はない
- 「最優先でやること」の最初の1行は、読んだ瞬間に着手したくなるレベルまで具体化する。曖昧な精神論は禁止
- 最新のノートに固有名詞候補（例: 直近のタイトル、テーマ候補、読書中の書籍名）があれば、その固有名詞を優先して使う
- アプリ名、URL、外部文、(Generated by MAGI System)、ダウンロード表記、ハッシュタグは本文に含めない
最新のノート:
$notesSummary
''';
}

String buildAiSecretaryShareText(String strategyResult) {
  final sanitizedLines = strategyResult.split('\n').where((line) {
    final trimmed = line.trim();
    if (trimmed.isEmpty) return true;
    if (trimmed == _shareTitle) return false;
    if (trimmed == _shareLead) return false;
    if (trimmed == _shareLeadSub) return false;
    if (trimmed == '(Generated by MAGI System)') return false;
    if (trimmed.startsWith('ダウンロード:')) return false;
    if (trimmed == '#自分株式会社') return false;
    return true;
  }).toList();

  final sanitizedBody = sanitizedLines.join('\n').trim();
  final body = sanitizedBody.isEmpty ? '生成結果がありません。' : sanitizedBody;

  return '$_shareTitle\n\n$_shareLead\n$_shareLeadSub\n\n$body\n\n$_shareFooter';
}
