import 'package:flutter_test/flutter_test.dart';
import 'package:my_web_app/utils/ai_secretary_content.dart';

void main() {
  test('buildAiSecretaryPrompt enforces one clear top priority', () {
    final prompt = buildAiSecretaryPrompt(
      strategyLabel: '今日',
      recentNotesJson: const [
        {
          'title': '読書メモ',
          'content': '次に日本国紀(上)を読み進めて、江戸時代の流れを整理したい。',
        },
      ],
    );

    expect(prompt, contains('## 最優先でやること'));
    expect(prompt, contains('## 理由'));
    expect(prompt, contains('## 48時間以内にやること'));
    expect(prompt, contains('## やらないこと'));
    expect(prompt, contains('「最優先でやること」は必ず1項目だけにする'));
    expect(
      prompt,
      contains('「ここまで次の一手が明確なら、このアプリを使いたい」と感じる'),
    );
    expect(prompt, contains('読書メモ'));
    expect(prompt, contains('日本国紀(上)'));
  });

  test('buildAiSecretaryShareText adds one CTA and one footer', () {
    final text = buildAiSecretaryShareText(
      '## 最優先でやること\n'
      '- **日本国紀(上)を20ページ読む**\n\n'
      '今日のやるべきことをAIと運営導線で1件に絞る。\n'
      '「自分株式会社」を使って人生を経営中。\n'
      '今すぐ試す → https://my-web-app-b67f4.web.app/\n'
      '(Generated by MAGI System)\n'
      'ダウンロード: https://my-web-app-b67f4.web.app/\n'
      '#自分株式会社',
    );

    expect(text, startsWith('【自分株式会社 経営戦略】'));
    expect(
      RegExp(r'今日のやるべきことをAIと運営導線で1件に絞る。').allMatches(text).length,
      1,
    );
    expect(
      RegExp(r'「自分株式会社」を使って人生を経営中。').allMatches(text).length,
      1,
    );
    expect(
      RegExp(r'今すぐ試す → https://my-web-app-b67f4.web.app/')
          .allMatches(text)
          .length,
      1,
    );
    expect(RegExp(r'\(Generated by MAGI System\)').allMatches(text).length, 1);
    expect(RegExp(r'#自分株式会社').allMatches(text).length, 1);
  });
}
