import 'package:flutter_test/flutter_test.dart';
import 'package:my_web_app/utils/ai_secretary_content.dart';

void main() {
  test('buildAiSecretaryPrompt enforces the requested markdown structure', () {
    final prompt = buildAiSecretaryPrompt(
      strategyLabel: '今日',
      recentNotesJson: const [
        {
          'title': '読書メモ',
          'content': '次に日本国紀(上)を読み進めて、江戸時代を深掘りしたい。',
        },
      ],
    );

    expect(prompt, contains('## 最優先でやること'));
    expect(prompt, contains('## 理由'));
    expect(prompt, contains('## 48時間以内にやること'));
    expect(prompt, contains('## やらないこと'));
    expect(prompt, contains('「48時間以内にやること」は2項目にする'));
    expect(
      prompt,
      contains(
        'アプリ名、URL、署名、(Generated by MAGI System)、ダウンロード表記、ハッシュタグは本文に含めない',
      ),
    );
    expect(prompt, contains('読書メモ'));
    expect(prompt, contains('日本国紀(上)'));
  });

  test('buildAiSecretaryShareText keeps only one standard footer', () {
    final text = buildAiSecretaryShareText(
      '## 最優先でやること\n'
      '- **日本国紀(上)** を読む\n\n'
      '(Generated by MAGI System)\n'
      ' ダウンロード: https://my-web-app-b67f4.web.app/\n'
      '#自分株式会社',
    );

    expect(text, startsWith('【自分株式会社 経営戦略】'));
    expect(RegExp(r'\(Generated by MAGI System\)').allMatches(text).length, 1);
    expect(
      RegExp(r'ダウンロード: https://my-web-app-b67f4.web.app')
          .allMatches(text)
          .length,
      1,
    );
    expect(RegExp(r'#自分株式会社').allMatches(text).length, 1);
  });
}
