import 'package:flutter_test/flutter_test.dart';
import 'package:my_web_app/utils/ai_secretary_content.dart';

void main() {
  test('buildAiSecretaryPrompt enforces persuasive markdown structure', () {
    final prompt = buildAiSecretaryPrompt(
      strategyLabel: '今日',
      recentNotesJson: const [
        {
          'title': '読書メモ',
          'content': '次に日本国紀(上)を読み進めて、江戸時代の社会構造を整理したい。',
        },
      ],
    );

    expect(prompt, contains('## 最優先でやること'));
    expect(prompt, contains('## 理由'));
    expect(prompt, contains('## 48時間以内にやること'));
    expect(prompt, contains('## やらないこと'));
    expect(
      prompt,
      contains('読み手が「このアプリなら次の一手がすぐ決まる」と感じるように'),
    );
    expect(
      prompt,
      contains('「最優先でやること」の最初の1行は、読んだ瞬間に着手したくなる'),
    );
    expect(prompt, contains('読書メモ'));
    expect(prompt, contains('日本国紀(上)'));
  });

  test('buildAiSecretaryShareText adds one persuasive lead and one footer', () {
    final text = buildAiSecretaryShareText(
      '## 最優先でやること\n'
      '- **日本国紀(上)を20ページ読む**\n\n'
      '迷いを減らして、次の一手まで一気に整理。\n'
      'このアプリなら、最優先・理由・48時間以内の行動がすぐ決まります。\n'
      '(Generated by MAGI System)\n'
      'ダウンロード: https://my-web-app-b67f4.web.app/\n'
      '#自分株式会社',
    );

    expect(text, startsWith('【自分株式会社 経営戦略】'));
    expect(RegExp(r'迷いを減らして、次の一手まで一気に整理。').allMatches(text).length, 1);
    expect(
      RegExp(r'このアプリなら、最優先・理由・48時間以内の行動がすぐ決まります。').allMatches(text).length,
      1,
    );
    expect(RegExp(r'\(Generated by MAGI System\)').allMatches(text).length, 1);
    expect(
      RegExp(r'ダウンロード: https://my-web-app-b67f4.web.app/')
          .allMatches(text)
          .length,
      1,
    );
    expect(RegExp(r'#自分株式会社').allMatches(text).length, 1);
  });
}
