#!/usr/bin/env python3
"""ai_tool_changelog_to_issues.py — H 重要度を GitHub Issue 化.

Win版#132 part 99 / 2026-04-30 / AI_FLEET_SYNERGY 原則 #3 dogfood.

Input:
  - docs/ai-tool-changelog/<month>.md  (= summarize.py が生成)

Action:
  - 「- [H] <title>」形式の行を抽出
  - 既存 ai-tool-update label issue と title 重複チェック (= 簡易 dedup)
  - 新規分のみ gh issue create
  - 月次 cross-instance draft bundle を docs/cross-instance-prs/drafts/ に生成

Logic:
  - GH_TOKEN 必須 (= GHA 内では自動)
  - label = ai-tool-update (label 不在なら作成)
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def gh(args: list[str], repo: str, capture: bool = True) -> tuple[int, str]:
    cmd = ["gh"] + args
    if "--repo" not in args:
        cmd.extend(["--repo", repo])
    try:
        r = subprocess.run(
            cmd,
            check=False,
            capture_output=capture,
            text=True,
            encoding="utf-8",
        )
        return r.returncode, (r.stdout if capture else "")
    except FileNotFoundError:
        return 127, "gh CLI not available"


def ensure_label(repo: str, label: str) -> None:
    """label が無ければ作成. 失敗は warning のみ."""
    code, out = gh(["label", "list", "--limit", "200"], repo)
    if code != 0:
        print(f"WARN: label list failed: {out}", file=sys.stderr)
        return
    if label in out:
        return
    code, _ = gh(
        ["label", "create", label, "--color", "00897B",
         "--description", "AI tool (Claude Code / Codex CLI) new feature monthly watch"],
        repo,
    )
    if code != 0:
        print(f"WARN: label create '{label}' failed", file=sys.stderr)


def existing_issue_titles(repo: str, label: str) -> set[str]:
    """同 label の現存 issue title を取得 (= dedup 用)."""
    code, out = gh(
        ["issue", "list", "--label", label, "--state", "all",
         "--limit", "500", "--json", "title"],
        repo,
    )
    if code != 0:
        return set()
    try:
        import json
        data = json.loads(out)
        return {i.get("title", "") for i in data}
    except Exception:  # noqa: BLE001
        return set()


def parse_h_items(md_path: Path) -> list[str]:
    """`- [H] <title>` パターンを抽出."""
    if not md_path.exists():
        return []
    items: list[str] = []
    pat = re.compile(r"^- \[H\][:\s]*(.+)$")
    for line in md_path.read_text(encoding="utf-8").splitlines():
        m = pat.match(line.strip())
        if m:
            title = normalize_h_title(m.group(1))
            if title:
                items.append(title)
    # dedup within file
    return list(dict.fromkeys(items))


def normalize_h_title(raw: str) -> str:
    """Markdown の太字/link suffix を落として issue/draft title にする."""
    title = raw.strip()
    title = re.sub(r"\s+(?:-|—)\s+\[link\].*$", "", title)
    title = re.sub(r"\s+—.*$", "", title)
    title = title.replace("**", "").strip()
    return title.rstrip("—- ").strip()


def month_from_input(md_path: Path) -> str:
    """docs/ai-tool-changelog/YYYY-MM.md から month tag を推定."""
    m = re.search(r"\d{4}-\d{2}", md_path.name)
    return m.group(0) if m else "unknown-month"


def repo_relative(path: Path) -> str:
    """GitHub issue body 用に repo root 相対 path を返す."""
    try:
        return path.relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def resolve_repo_path(path_text: str) -> Path:
    path = Path(path_text)
    if path.is_absolute():
        return path
    return REPO_ROOT / path


def write_cross_instance_draft(md_path: Path, input_arg: str,
                               items: list[str], draft_dir: Path) -> str:
    """H items を 2-instance flow 用の monthly draft bundle として残す."""
    month = month_from_input(md_path)
    draft_dir.mkdir(parents=True, exist_ok=True)
    out_path = draft_dir / f"{month}_ai_tool_update_cross_instance_drafts.md"

    lines: list[str] = [
        f"# AI Tool Update Cross-Instance Drafts {month}",
        "",
        "Auto-generated by `scripts/ai_tool_changelog_to_issues.py`.",
        "",
        f"Source summary: `{input_arg}`",
        "",
        "Canonical flow:",
        "- Claude Code #1 reviews adoption, WBS priority, and product/process risk.",
        "- Codex #1 owns scoped implementation, CI, merge follow-up, and cleanup.",
        "- Dormant historical lanes such as Codex #2 are not live owners.",
        "",
        "## H-Priority Candidates",
        "",
    ]

    for idx, title in enumerate(items, 1):
        issue_title = f"[ai-tool-update] {title}"
        lines.extend([
            f"### {idx}. {title}",
            "",
            f"- Issue title: `{issue_title}`",
            "- Claude Code #1 decision: adopt / defer / ignore.",
            "- Codex #1 implementation trigger: start only after the decision is clear.",
            "- Expected PR shape: narrow docs/workflow/script update with deterministic checks.",
            "",
        ])

    lines.extend([
        "## Delegation Packet Template",
        "",
        "```markdown",
        "## Delegation Packet",
        "",
        "- WBS / Issue:",
        "- Due date:",
        "- Current owner: Claude Code #1 / Codex #1 / User / Automation",
        "- Objective:",
        "- Branch:",
        "- Worktree:",
        "- Allowed write set:",
        "- Prohibited write set:",
        "- Required validation:",
        "- Expected output:",
        "- Risk triggers that must return to Claude Code:",
        "- Memory/disk hygiene action for this session:",
        "",
        "## Result Contract",
        "",
        "- Changed files:",
        "- Validation result:",
        "- PR / Issue links:",
        "- Remaining risk:",
        "- Next owner:",
        "```",
        "",
    ])

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return repo_relative(out_path)


def create_issue(repo: str, label: str, title: str, body: str) -> bool:
    full_title = f"[ai-tool-update] {title}"
    code, out = gh(
        ["issue", "create", "--title", full_title,
         "--body", body, "--label", label],
        repo,
        capture=True,
    )
    if code == 0:
        print(f"created: {full_title}")
        return True
    print(f"WARN: issue create failed: {out}", file=sys.stderr)
    return False


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--input", required=True)
    p.add_argument("--label", default="ai-tool-update")
    p.add_argument("--repo", required=True)
    p.add_argument(
        "--draft-dir",
        default="docs/cross-instance-prs/drafts/ai-tool-update",
        help="repo-relative directory for monthly cross-instance draft bundles",
    )
    args = p.parse_args()

    md_path = REPO_ROOT / args.input

    ensure_label(args.repo, args.label)
    existing = existing_issue_titles(args.repo, args.label)

    items = parse_h_items(md_path)
    if not items:
        print("no H-priority items / no issue creation")
        return 0

    draft_rel = write_cross_instance_draft(
        md_path,
        args.input,
        items,
        resolve_repo_path(args.draft_dir),
    )

    body_template = (
        "Auto-generated by `scripts/ai_tool_changelog_to_issues.py` "
        "(= AI_FLEET_SYNERGY #3 dogfood).\n\n"
        f"Source summary: `{args.input}`\n\n"
        f"Cross-instance draft bundle: `{draft_rel}`\n\n"
        "## 検討項目\n\n"
        "- [ ] fleet にこの機能を取込むべきか?\n"
        "- [ ] 取込時の cross-instance-pr 起票候補?\n"
        "- [ ] CLAUDE.md routing matrix 更新が必要?\n"
    )

    created = 0
    for title in items:
        full_title = f"[ai-tool-update] {title}"
        if full_title in existing:
            print(f"skip (exists): {full_title}")
            continue
        if create_issue(args.repo, args.label, title, body_template):
            created += 1

    print(f"summary: {created} new issue(s) created from {len(items)} H items")
    return 0


if __name__ == "__main__":
    sys.exit(main())
