#!/usr/bin/env python3
"""build_in_public_extract.py — ROADMAP-LOG から外部発信 draft 生成 (Win版#132 part 112).

WBS Issue #1125 / INDIE_DEV_VELOCITY #7 (Community Engagement Discipline) dogfood.

目的:
  AI 開発成果を「発信可能な実績」に変換. ROADMAP-LOG の直近 N 日を
  scan して dev.to 投稿用 markdown / X 投稿用短文 / GitHub Discussion 用
  summary を **自動 draft** 生成.

inputs:
  - docs/GROWTH_STRATEGY_ROADMAP.md (= ROADMAP-LOG / 既存)
  - memory/log.md (= Daily Log / part 69 確立 / SECOND_BRAIN dogfood)

outputs:
  - docs/build-in-public/<YYYY-MM-DD>_devto_draft.md
  - docs/build-in-public/<YYYY-MM-DD>_x_draft.txt
  - docs/build-in-public/<YYYY-MM-DD>_summary.md (= 統合 summary)

= 「AI 生成だけど CEO が承認 → 投稿」フロー想定. PS#2 T-1 dispatch routine と連携.
"""

from __future__ import annotations

import argparse
import re
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
ROADMAP_PATH = REPO_ROOT / "docs" / "GROWTH_STRATEGY_ROADMAP.md"
LOG_PATH = Path("C:/Users/kanta/.claude/projects/C--Users-kanta-GitHub-my-web-app/memory/log.md")
if not LOG_PATH.exists():
    LOG_PATH = REPO_ROOT / "memory" / "log.md"


def extract_recent_roadmap_entries(days: int = 7) -> list[str]:
    """ROADMAP-LOG から直近 N 日分 entry を抽出 (= H2 + 内容 block)."""
    if not ROADMAP_PATH.exists():
        return []
    text = ROADMAP_PATH.read_text(encoding="utf-8", errors="replace")
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    cutoff_str = cutoff.strftime("%Y-%m-%d")
    # H2 = ## YYYY-MM-DD ... 形式想定
    blocks = re.split(r"^(##\s+\d{4}-\d{2}-\d{2}.*$)", text, flags=re.MULTILINE)
    out: list[str] = []
    i = 1
    while i < len(blocks):
        header = blocks[i].strip()
        body = blocks[i + 1] if i + 1 < len(blocks) else ""
        m = re.match(r"##\s+(\d{4}-\d{2}-\d{2})", header)
        if m and m.group(1) >= cutoff_str:
            out.append(header + "\n" + body.strip())
        i += 2
    return out


def extract_recent_log_entries(days: int = 7) -> list[str]:
    """memory/log.md から直近 N 日分 entry を抽出 (= ## [YYYY-MM-DD ...] header block)."""
    if not LOG_PATH.exists():
        return []
    text = LOG_PATH.read_text(encoding="utf-8", errors="replace")
    cutoff = datetime.now(timezone.utc) - timedelta(days=days)
    cutoff_str = cutoff.strftime("%Y-%m-%d")
    blocks = re.split(r"^(##\s+\[\d{4}-\d{2}-\d{2}.*\].*$)", text, flags=re.MULTILINE)
    out: list[str] = []
    i = 1
    while i < len(blocks):
        header = blocks[i].strip()
        body = blocks[i + 1] if i + 1 < len(blocks) else ""
        m = re.search(r"\[(\d{4}-\d{2}-\d{2})", header)
        if m and m.group(1) >= cutoff_str:
            out.append(header + "\n" + body.strip())
        i += 2
    return out


def render_devto_draft(entries: list[str], days: int) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    lines: list[str] = []
    lines.append("---")
    lines.append("title: Building 自分株式会社 — Last %d Days of AI Fleet Development" % days)
    lines.append("published: false")
    lines.append("tags: ai, indiedev, buildinpublic, claude")
    lines.append(f"date: {today}")
    lines.append("---")
    lines.append("")
    lines.append("## TL;DR")
    lines.append("")
    lines.append(
        f"Last {days} days of building **自分株式会社** "
        f"(= Jibun Inc. / a personal life-management AI app) with a "
        f"**12-instance AI fleet** (10 Claude Code + 2 Codex CLI). "
        f"This post extracts the recent ROADMAP-LOG entries as a "
        f"build-in-public update."
    )
    lines.append("")
    lines.append("## Recent activity (auto-extracted)")
    lines.append("")
    if entries:
        for entry in entries[:10]:
            lines.append(entry)
            lines.append("")
            lines.append("---")
            lines.append("")
    else:
        lines.append("- (no entries found in window)")
    lines.append("")
    lines.append("## Stack")
    lines.append("")
    lines.append("- Frontend: Flutter Web (Dart)")
    lines.append("- Backend: Supabase (PostgreSQL + Edge Functions / Deno)")
    lines.append("- Hosting: Firebase Hosting")
    lines.append("- AI: Claude Code (10 instances) + Codex CLI (2 instances)")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/build_in_public_extract.py` "
        "(= INDIE_DEV_VELOCITY #7 Community Engagement Discipline dogfood).\n"
    )
    return "\n".join(lines)


def render_x_draft(entries: list[str], days: int) -> str:
    """X 投稿用 280-char 程度の短文."""
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    titles = []
    for entry in entries[:5]:
        m = re.search(r"^##\s+(?:\[)?\d{4}-\d{2}-\d{2}.*?(?:\])?\s*(.+?)$",
                      entry, flags=re.MULTILINE)
        if m:
            titles.append(m.group(1).strip()[:60])
    body = (
        f"自分株式会社 (= Jibun Inc.) 最近 {days} 日:\n"
        + "\n".join(f"- {t}" for t in titles[:3])
        + "\n\n"
        f"#buildinpublic #flutter #supabase #claudecode #aifleet"
    )
    return body[:280]


def render_summary(roadmap: list[str], log: list[str], days: int) -> str:
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    return f"""# Build in Public Summary {today} (last {days} days)

> Auto-generated by `scripts/build_in_public_extract.py` for WBS Issue #1125 + INDIE_DEV_VELOCITY #7.

## ROADMAP-LOG entries: {len(roadmap)}
## memory/log.md entries: {len(log)}

## Generated artifacts

- `<date>_devto_draft.md` — dev.to 投稿用 draft (= manual review 後 PS#2 が dispatch)
- `<date>_x_draft.txt` — X (Twitter) 投稿用 短文
- `<date>_summary.md` — 本 file (= 統合 summary)

## Recommended workflow

1. CEO review devto_draft.md → 修正 → publish via dev.to
2. CEO review x_draft.txt → 投稿
3. monthly cron 化候補 (= future / `.github/workflows/build-in-public.yml`)

## Stats (= last {days} days)

- ROADMAP entries: {len(roadmap)}
- Daily log entries: {len(log)}
- Total markdown lines (approx): {sum(len(e.splitlines()) for e in roadmap + log)}

---

*part 112 dogfood / INDIE_DEV_VELOCITY #7 dogfood*
"""


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--days", type=int, default=7)
    p.add_argument("--out-dir", default="docs/build-in-public")
    args = p.parse_args()

    roadmap = extract_recent_roadmap_entries(args.days)
    log = extract_recent_log_entries(args.days)
    combined = roadmap + log

    out_dir = REPO_ROOT / args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    today = datetime.now(timezone.utc).strftime("%Y-%m-%d")

    devto = render_devto_draft(combined, args.days)
    x = render_x_draft(combined, args.days)
    summary = render_summary(roadmap, log, args.days)

    devto_path = out_dir / f"{today}_devto_draft.md"
    x_path = out_dir / f"{today}_x_draft.txt"
    summary_path = out_dir / f"{today}_summary.md"
    devto_path.write_text(devto, encoding="utf-8")
    x_path.write_text(x, encoding="utf-8")
    summary_path.write_text(summary, encoding="utf-8")

    print(f"wrote {devto_path}")
    print(f"wrote {x_path}")
    print(f"wrote {summary_path}")
    print(f"roadmap entries: {len(roadmap)} / log entries: {len(log)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
