import 'dart:io';

class AnalyzerLogSummary {
  final String finalError;
  final String? exitCode;
  final List<String> tail;

  const AnalyzerLogSummary({
    required this.finalError,
    required this.exitCode,
    required this.tail,
  });
}

class BugReportInput {
  final String title;
  final String expected;
  final String reproductionSteps;
  final String logPath;
  final String logContent;
  final String dartVersion;
  final String dartInfo;
  final String osInfo;

  const BugReportInput({
    required this.title,
    required this.expected,
    required this.reproductionSteps,
    required this.logPath,
    required this.logContent,
    required this.dartVersion,
    required this.dartInfo,
    required this.osInfo,
  });
}

Future<void> main(List<String> args) async {
  final parsed = _parseArgs(args);
  if (parsed.containsKey('help')) {
    stdout.writeln(_usage());
    return;
  }

  final logPath = parsed['log'] ?? '';
  final logContent = logPath.isEmpty
      ? ''
      : await File(logPath).readAsString().catchError(
            (_) => 'Failed to read log file: $logPath',
          );
  final input = BugReportInput(
    title: parsed['title'] ?? 'Dart Analyzer terminated unexpectedly',
    expected: parsed['expected'] ??
        'The Dart analyzer should keep running and report diagnostics without terminating.',
    reproductionSteps: parsed['repro'] ??
        '1. Open this Flutter project in VS Code.\n'
            '2. Start Dart analysis or edit a Dart file.\n'
            '3. Observe the analyzer termination in the VS Code / Dart logs.',
    logPath: logPath.isEmpty ? '(not provided)' : logPath,
    logContent: logContent,
    dartVersion: await _runCapture('dart', const <String>['--version']),
    dartInfo: await _runCapture('dart', const <String>['info']),
    osInfo: defaultOsInfo(),
  );

  final markdown = buildDartSdkBugReport(input);
  stdout.writeln(markdown);
  if (parsed.containsKey('copy')) {
    await copyToClipboard(markdown);
    stderr.writeln('Copied Dart SDK bug report Markdown to clipboard.');
  }
}

AnalyzerLogSummary parseAnalyzerLog(String content, {int tailLines = 30}) {
  final normalized = content.replaceAll('\r\n', '\n').replaceAll('\r', '\n');
  final lines = normalized
      .split('\n')
      .map((line) => line.trimRight())
      .where((line) => line.trim().isNotEmpty)
      .toList();
  if (lines.isEmpty) {
    return const AnalyzerLogSummary(
      finalError: 'No analyzer log content was provided.',
      exitCode: null,
      tail: <String>[],
    );
  }

  String? exitCode;
  final exitPatterns = <RegExp>[
    RegExp(
      r'exit(?:ed)?(?:\s+with)?\s+code[:\s]+(-?\d+)',
      caseSensitive: false,
    ),
    RegExp(r'code[:\s]+(-?\d{4,})', caseSensitive: false),
    RegExp(r'\b(3221226505|3221225477|134|139)\b'),
  ];
  for (final line in lines.reversed) {
    for (final pattern in exitPatterns) {
      final match = pattern.firstMatch(line);
      if (match != null) {
        exitCode = match.group(1);
        break;
      }
    }
    if (exitCode != null) break;
  }

  final finalError = lines.reversed.firstWhere(
    (line) => !_looksLikeExitOnlyLine(line),
    orElse: () => lines.last,
  );
  final start = lines.length > tailLines ? lines.length - tailLines : 0;
  return AnalyzerLogSummary(
    finalError: finalError,
    exitCode: exitCode,
    tail: lines.sublist(start),
  );
}

String buildDartSdkBugReport(BugReportInput input) {
  final summary = parseAnalyzerLog(input.logContent);
  final exitCode = summary.exitCode ?? 'not found';
  final tail =
      summary.tail.isEmpty ? 'No log tail available.' : summary.tail.join('\n');
  return '''
# ${input.title}

## Expected behavior
${input.expected}

## Actual behavior
The Dart analyzer terminated while working in this project.

- Final error line: `${_inlineCode(summary.finalError)}`
- Exit code: `$exitCode`
- Source log: `${_inlineCode(input.logPath)}`

## Reproduction steps
${input.reproductionSteps}

## Analyzer log tail
```text
$tail
```

## Environment
```text
${input.osInfo}

${input.dartVersion}
```

## dart info
```text
${input.dartInfo}
```

## Additional context
This report was generated by `scripts/dart_sdk_bug_report.dart` so that repeated analyzer crashes can be filed to dart-lang/sdk without manually rebuilding environment and log context.
''';
}

String defaultOsInfo() {
  return [
    'OS: ${Platform.operatingSystem} ${Platform.operatingSystemVersion}',
    'Locale: ${Platform.localeName}',
    'Executable: ${Platform.executable}',
    'Dart executable arguments: ${Platform.executableArguments.join(' ')}',
  ].join('\n');
}

Future<void> copyToClipboard(String text) async {
  if (Platform.isWindows) {
    final process = await Process.start('clip', const <String>[]);
    process.stdin.write(text);
    await process.stdin.close();
    await process.exitCode;
    return;
  }
  if (Platform.isMacOS) {
    final process = await Process.start('pbcopy', const <String>[]);
    process.stdin.write(text);
    await process.stdin.close();
    await process.exitCode;
    return;
  }
  final xclip = await Process.run('which', const <String>['xclip']);
  if (xclip.exitCode == 0) {
    final process = await Process.start(
      'xclip',
      const <String>['-selection', 'clipboard'],
    );
    process.stdin.write(text);
    await process.stdin.close();
    await process.exitCode;
    return;
  }
  throw UnsupportedError('No clipboard command found for this platform.');
}

Future<String> _runCapture(String executable, List<String> args) async {
  try {
    final result = await Process.run(executable, args);
    final output = [
      result.stdout.toString().trim(),
      result.stderr.toString().trim(),
    ].where((part) => part.isNotEmpty).join('\n');
    return output.isEmpty
        ? '$executable ${args.join(' ')} produced no output.'
        : output;
  } catch (error) {
    return 'Failed to run $executable ${args.join(' ')}: $error';
  }
}

Map<String, String> _parseArgs(List<String> args) {
  final parsed = <String, String>{};
  for (var i = 0; i < args.length; i++) {
    final arg = args[i];
    if (arg == '--help' || arg == '-h') {
      parsed['help'] = 'true';
      continue;
    }
    if (arg == '--copy') {
      parsed['copy'] = 'true';
      continue;
    }
    if (arg.startsWith('--')) {
      final key = arg.substring(2);
      if (i + 1 >= args.length || args[i + 1].startsWith('--')) {
        parsed[key] = '';
      } else {
        parsed[key] = args[++i];
      }
    }
  }
  return parsed;
}

String _usage() {
  return '''
Usage:
  dart run scripts/dart_sdk_bug_report.dart --log <path> [options]

Options:
  --title <text>      Issue title.
  --expected <text>   Expected behavior.
  --repro <text>      Reproduction steps Markdown.
  --copy              Copy generated Markdown to the clipboard.
  --help              Show this help.
''';
}

bool _looksLikeExitOnlyLine(String line) {
  final lower = line.toLowerCase();
  return lower.contains('exit code') ||
      lower.contains('exited with code') ||
      RegExp(r'^code[:\s]+-?\d+$', caseSensitive: false).hasMatch(line);
}

String _inlineCode(String value) {
  return value.replaceAll('`', r'\`');
}
