#!/usr/bin/env python3
"""Open or update the canonical Issue when daily-report artifacts go stale."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path
from typing import Any


DEFAULT_TITLE = "[Schedule監視] daily-report タスク未実行を検出"
DEFAULT_LABELS = ("bug", "automation", "priority:high")


def read_json_text(path: Path) -> str:
    data = path.read_bytes()
    for encoding in ("utf-8-sig", "utf-16"):
        try:
            return data.decode(encoding)
        except UnicodeDecodeError:
            continue
    return data.decode("utf-8", errors="replace")


def load_json(path: Path) -> dict[str, Any]:
    data = json.loads(read_json_text(path))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must contain a JSON object")
    return data


def find_matching_issue(open_issues: list[dict[str, Any]], title: str) -> dict[str, Any] | None:
    for issue in open_issues:
        if str(issue.get("title", "")).strip() == title:
            return issue
    return None


def decide_action(
    freshness: dict[str, Any],
    open_issues: list[dict[str, Any]],
    title: str = DEFAULT_TITLE,
) -> dict[str, Any]:
    if freshness.get("fresh") is True:
        return {"action": "none", "reason": "daily-report artifacts are fresh"}

    existing = find_matching_issue(open_issues, title)
    if existing:
        return {
            "action": "comment",
            "issue_number": existing.get("number"),
            "issue_url": existing.get("url", ""),
            "reason": "canonical open Issue already exists",
        }
    return {
        "action": "create",
        "issue_number": "",
        "issue_url": "",
        "reason": "no canonical open Issue found",
    }


def run_gh(args: list[str], body: str | None = None) -> str:
    result = subprocess.run(
        ["gh", *args],
        input=body,
        encoding="utf-8",
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(result.stderr.strip() or f"gh {' '.join(args)} failed")
    return result.stdout.strip()


def load_open_issues(repo: str, title: str, issues_json: Path | None) -> list[dict[str, Any]]:
    if issues_json:
        data = json.loads(read_json_text(issues_json))
        issues = data.get("issues", data) if isinstance(data, dict) else data
        if isinstance(issues, list):
            return [item for item in issues if isinstance(item, dict)]
        raise ValueError(f"{issues_json} must contain a JSON list or an object with an issues list")

    output = run_gh(
        [
            "issue",
            "list",
            "--repo",
            repo,
            "--state",
            "open",
            "--search",
            f'"{title}" in:title',
            "--limit",
            "50",
            "--json",
            "number,title,url",
        ]
    )
    data = json.loads(output or "[]")
    return data if isinstance(data, list) else []


def render_body(freshness: dict[str, Any], workflow_url: str, mode: str) -> str:
    date = freshness.get("date", "unknown")
    ref = freshness.get("ref", "unknown")
    reason = freshness.get("reason", "unknown")
    signals = freshness.get("signals", {})
    paths = freshness.get("paths", {})

    lines = [
        f"## daily-report freshness alert ({date})",
        "",
        f"- **Mode**: {mode}",
        f"- **Ref checked**: `{ref}`",
        f"- **Reason**: {reason}",
        f"- **Workflow run**: {workflow_url or '(local/dry-run)'}",
        "",
        "## Signals",
    ]
    if isinstance(signals, dict):
        for key, value in signals.items():
            lines.append(f"- `{key}`: `{str(value).lower()}`")
    else:
        lines.append("- `(invalid signals payload)`")

    lines.extend(["", "## Checked Paths"])
    if isinstance(paths, dict):
        for key, value in paths.items():
            lines.append(f"- `{key}`: `{value}`")
    else:
        lines.append("- `(invalid paths payload)`")

    lines.extend(
        [
            "",
            "## Action Required",
            "- Inspect `daily-report.yml` if the scheduled run failed or did not push artifacts.",
            "- Confirm whether `docs/daily-reports/<date>.md`, `docs/metrics/daily-metrics.json`, or schedule logs were updated on `main`.",
            "- Keep this canonical Issue open while the freshness monitor still reports stale output; avoid creating duplicate daily-report outage Issues.",
            "",
            "_Auto-generated by `daily-report-freshness-monitor.yml`._",
        ]
    )
    return "\n".join(lines)


def write_outputs(path: str | None, plan: dict[str, Any]) -> None:
    if not path:
        return
    with open(path, "a", encoding="utf-8") as handle:
        for key in ("action", "issue_number", "issue_url", "reason"):
            handle.write(f"{key}={plan.get(key, '')}\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--freshness-json", required=True, help="JSON output from check_daily_report_freshness.py")
    parser.add_argument("--repo", default=os.environ.get("GITHUB_REPOSITORY", "kanta13jp1/my_web_app"))
    parser.add_argument("--title", default=DEFAULT_TITLE)
    parser.add_argument("--labels", default=",".join(DEFAULT_LABELS))
    parser.add_argument("--issues-json", help="Optional test fixture for open Issues")
    parser.add_argument("--workflow-url", default="")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument(
        "--github-output",
        default=os.environ.get("GITHUB_OUTPUT"),
        help="Optional GitHub Actions output file",
    )
    args = parser.parse_args()

    freshness = load_json(Path(args.freshness_json))
    open_issues = load_open_issues(
        args.repo,
        args.title,
        Path(args.issues_json) if args.issues_json else None,
    )
    plan = decide_action(freshness, open_issues, args.title)
    body = render_body(freshness, args.workflow_url, plan["action"])

    if args.dry_run or plan["action"] == "none":
        print(json.dumps(plan, ensure_ascii=False, indent=2))
        if plan["action"] != "none":
            print("\n--- issue body ---\n")
            print(body)
        write_outputs(args.github_output, plan)
        return 0

    if plan["action"] == "comment":
        issue_number = str(plan["issue_number"])
        url = run_gh(
            ["issue", "comment", issue_number, "--repo", args.repo, "--body-file", "-"],
            body,
        )
        plan["issue_url"] = url or plan.get("issue_url", "")
    elif plan["action"] == "create":
        url = run_gh(
            [
                "issue",
                "create",
                "--repo",
                args.repo,
                "--title",
                args.title,
                "--label",
                args.labels,
                "--body-file",
                "-",
            ],
            body,
        )
        plan["issue_url"] = url
    else:
        raise RuntimeError(f"unsupported action: {plan['action']}")

    print(json.dumps(plan, ensure_ascii=False, indent=2))
    write_outputs(args.github_output, plan)
    return 0


if __name__ == "__main__":
    sys.exit(main())
