#!/usr/bin/env python3
"""Build and verify evidence for encrypted Supabase logical backups."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
from datetime import datetime, timezone
from pathlib import Path


BACKUP_FILES = ("roles.sql", "schema.sql", "data.sql")
COPY_START = re.compile(
    r'^COPY\s+"(?P<schema>(?:[^"]|"")+)"\."(?P<table>(?:[^"]|"")+)"'
    r"\s+\(.+\)\s+FROM stdin;$"
)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_manifest(
    input_dir: Path,
    project_ref: str,
    *,
    generated_at: str | None = None,
) -> dict[str, object]:
    files: list[dict[str, object]] = []
    for name in BACKUP_FILES:
        path = input_dir / name
        if not path.is_file() or path.stat().st_size == 0:
            raise ValueError(f"missing or empty backup file: {path}")
        files.append(
            {
                "name": name,
                "bytes": path.stat().st_size,
                "sha256": sha256(path),
            }
        )
    return {
        "schema_version": 1,
        "source_project_ref": project_ref,
        "generated_at_utc": generated_at
        or datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "files": files,
    }


def verify_manifest(input_dir: Path, manifest: dict[str, object]) -> None:
    raw_files = manifest.get("files")
    if not isinstance(raw_files, list) or not raw_files:
        raise ValueError("manifest has no files")
    for raw in raw_files:
        if not isinstance(raw, dict):
            raise ValueError("invalid file entry in manifest")
        name = str(raw.get("name") or "")
        if name not in BACKUP_FILES:
            raise ValueError(f"unexpected backup file in manifest: {name}")
        path = input_dir / name
        if not path.is_file():
            raise ValueError(f"backup file is missing after decrypt: {name}")
        if path.stat().st_size != int(raw.get("bytes") or -1):
            raise ValueError(f"backup file size mismatch: {name}")
        if sha256(path) != str(raw.get("sha256") or ""):
            raise ValueError(f"backup file digest mismatch: {name}")


def parse_copy_row_counts(
    data_sql: Path,
    schema: str,
    *,
    require_blocks: bool = True,
) -> dict[str, int]:
    counts: dict[str, int] = {}
    active_table: str | None = None
    with data_sql.open("r", encoding="utf-8", errors="strict", newline="") as handle:
        for raw_line in handle:
            line = raw_line.rstrip("\r\n")
            if active_table is not None:
                if line == r"\.":
                    active_table = None
                else:
                    counts[active_table] += 1
                continue

            match = COPY_START.match(line)
            if not match:
                continue
            copy_schema = match.group("schema").replace('""', '"')
            if copy_schema != schema:
                continue
            active_table = match.group("table").replace('""', '"')
            if active_table in counts:
                raise ValueError(f"duplicate COPY block: {schema}.{active_table}")
            counts[active_table] = 0

    if active_table is not None:
        raise ValueError(f"unterminated COPY block: {schema}.{active_table}")
    if require_blocks and not counts:
        raise ValueError(f"no COPY blocks found for schema: {schema}")
    return counts


def quote_identifier(value: str) -> str:
    return '"' + value.replace('"', '""') + '"'


def quote_literal(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def build_assertions_sql(counts: dict[str, int], schema: str) -> str:
    blocks = [
        "-- Generated by scripts/supabase_backup_verify.py; do not edit.",
        "\\set ON_ERROR_STOP on",
    ]
    schema_identifier = quote_identifier(schema)
    for table, expected in sorted(counts.items()):
        qualified = f"{schema_identifier}.{quote_identifier(table)}"
        label = quote_literal(f"restore row-count mismatch: {schema}.{table}")
        blocks.extend(
            [
                "DO $backup_restore_check$",
                "DECLARE",
                "  actual_count bigint;",
                "BEGIN",
                f"  SELECT count(*) INTO actual_count FROM {qualified};",
                f"  IF actual_count <> {expected} THEN",
                f"    RAISE EXCEPTION {label};",
                "  END IF;",
                "END",
                "$backup_restore_check$;",
            ]
        )
    return "\n".join(blocks) + "\n"


def infer_pgmq_queue_names(counts: dict[str, int]) -> list[str]:
    archive_queues = {table[2:] for table in counts if table.startswith("a_")}
    active_queues = {table[2:] for table in counts if table.startswith("q_")}
    if archive_queues != active_queues:
        missing_archive = sorted(active_queues - archive_queues)
        missing_active = sorted(archive_queues - active_queues)
        details = []
        if missing_archive:
            details.append(f"missing archive table(s): {', '.join(missing_archive)}")
        if missing_active:
            details.append(f"missing active table(s): {', '.join(missing_active)}")
        raise ValueError("incomplete PGMQ queue dump: " + "; ".join(details))
    return sorted(active_queues)


def build_pgmq_bootstrap_sql(
    queue_names: list[str],
    *,
    restore_meta: bool,
) -> str:
    blocks = [
        "-- Generated by scripts/supabase_backup_verify.py; do not edit.",
        "\\set ON_ERROR_STOP on",
    ]
    for queue_name in queue_names:
        active_table = f"q_{queue_name}"
        archive_table = f"a_{queue_name}"
        active_regclass = quote_literal(
            f'{quote_identifier("pgmq")}.{quote_identifier(active_table)}'
        )
        archive_regclass = quote_literal(
            f'{quote_identifier("pgmq")}.{quote_identifier(archive_table)}'
        )
        queue_literal = quote_literal(queue_name)
        error_literal = quote_literal(
            f"incomplete PGMQ target queue before restore: {queue_name}"
        )
        blocks.extend(
            [
                "DO $backup_restore_pgmq$",
                "BEGIN",
                f"  IF to_regclass({active_regclass}) IS NULL",
                f"     AND to_regclass({archive_regclass}) IS NULL THEN",
                f"    PERFORM pgmq.create({queue_literal});",
                f"  ELSIF to_regclass({active_regclass}) IS NULL",
                f"     OR to_regclass({archive_regclass}) IS NULL THEN",
                f"    RAISE EXCEPTION {error_literal};",
                "  END IF;",
                "END",
                "$backup_restore_pgmq$;",
            ]
        )
    if queue_names and restore_meta:
        queue_literals = ", ".join(quote_literal(name) for name in queue_names)
        blocks.append(
            'DELETE FROM "pgmq"."meta" '
            f'WHERE "queue_name" IN ({queue_literals});'
        )
    return "\n".join(blocks) + "\n"


def build_pgmq_finalize_sql(
    queue_names: list[str],
    counts: dict[str, int],
) -> str:
    blocks = [
        "-- Generated by scripts/supabase_backup_verify.py; do not edit.",
        "\\set ON_ERROR_STOP on",
    ]
    for queue_name in queue_names:
        table = f"q_{queue_name}"
        qualified = f'{quote_identifier("pgmq")}.{quote_identifier(table)}'
        qualified_literal = quote_literal(qualified)
        queue_literal = quote_literal(queue_name)
        error_literal = quote_literal(
            f"PGMQ message sequence is missing after restore: {queue_name}"
        )
        mode_error_literal = quote_literal(
            f"unsupported partitioned or unlogged PGMQ queue in restore: {queue_name}"
        )
        blocks.extend(
            [
                "DO $backup_restore_pgmq_mode$",
                "DECLARE",
                "  source_is_partitioned boolean;",
                "  source_is_unlogged boolean;",
                "BEGIN",
                '  SELECT "is_partitioned", "is_unlogged"',
                "    INTO STRICT source_is_partitioned, source_is_unlogged",
                f'    FROM "pgmq"."meta" WHERE "queue_name" = {queue_literal};',
                "  IF source_is_partitioned OR source_is_unlogged THEN",
                f"    RAISE EXCEPTION {mode_error_literal};",
                "  END IF;",
                "END",
                "$backup_restore_pgmq_mode$;",
                "DO $backup_restore_pgmq_sequence$",
                "DECLARE",
                "  sequence_name text;",
                "  maximum_message_id bigint;",
                "  has_messages boolean;",
                "BEGIN",
                f"  sequence_name := pg_get_serial_sequence({qualified_literal}, 'msg_id');",
                "  IF sequence_name IS NULL THEN",
                f"    RAISE EXCEPTION {error_literal};",
                "  END IF;",
                f'  SELECT max("msg_id"), EXISTS (SELECT 1 FROM {qualified})',
                f"    INTO maximum_message_id, has_messages FROM {qualified};",
                "  PERFORM setval(",
                "    sequence_name::regclass,",
                "    COALESCE(maximum_message_id, 1),",
                "    has_messages",
                "  );",
                "END",
                "$backup_restore_pgmq_sequence$;",
            ]
        )
    assertion_sql = build_assertions_sql(counts, "pgmq").splitlines()
    blocks.extend(assertion_sql[2:])
    return "\n".join(blocks) + "\n"


def write_json(path: Path, payload: dict[str, object]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def read_json(path: Path) -> dict[str, object]:
    payload = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ValueError(f"expected JSON object: {path}")
    return payload


def command_manifest(args: argparse.Namespace) -> None:
    write_json(
        args.output,
        build_manifest(args.input_dir, args.project_ref, generated_at=args.generated_at),
    )


def command_verify(args: argparse.Namespace) -> None:
    verify_manifest(args.input_dir, read_json(args.manifest))
    print("OK: decrypted backup files match manifest")


def command_assertions(args: argparse.Namespace) -> None:
    counts = parse_copy_row_counts(args.data_sql, args.schema)
    args.output.write_text(
        build_assertions_sql(counts, args.schema), encoding="utf-8"
    )
    print(f"ASSERTION_COUNT={len(counts)}")


def command_pgmq_restore(args: argparse.Namespace) -> None:
    counts = parse_copy_row_counts(args.data_sql, "pgmq", require_blocks=False)
    queue_names = infer_pgmq_queue_names(counts)
    args.bootstrap_output.write_text(
        build_pgmq_bootstrap_sql(queue_names, restore_meta="meta" in counts),
        encoding="utf-8",
    )
    args.finalize_output.write_text(
        build_pgmq_finalize_sql(queue_names, counts), encoding="utf-8"
    )
    print(f"PGMQ_QUEUE_COUNT={len(queue_names)}")
    print(f"PGMQ_ASSERTION_COUNT={len(counts)}")


def command_evidence(args: argparse.Namespace) -> None:
    manifest = read_json(args.manifest)
    assertion_count = sum(
        1
        for line in args.assertions.read_text(encoding="utf-8").splitlines()
        if line == "DO $backup_restore_check$"
    )
    if assertion_count < 1:
        raise ValueError("restore assertions were not generated")
    pgmq_assertion_count = sum(
        1
        for line in args.pgmq_finalize.read_text(encoding="utf-8").splitlines()
        if line == "DO $backup_restore_check$"
    )
    pgmq_queue_count = sum(
        1
        for line in args.pgmq_bootstrap.read_text(encoding="utf-8").splitlines()
        if line.strip().startswith("PERFORM pgmq.create(")
    )
    write_json(
        args.output,
        {
            "schema_version": 1,
            "source_project_ref": manifest.get("source_project_ref"),
            "backup_generated_at_utc": manifest.get("generated_at_utc"),
            "verified_at_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "github_run_id": args.run_id,
            "github_run_attempt": args.run_attempt,
            "encrypted_bundle_sha256": sha256(args.archive),
            "restore_target": "ephemeral-local-supabase",
            "public_table_assertions": assertion_count,
            "pgmq_table_assertions": pgmq_assertion_count,
            "pgmq_queues_recreated": pgmq_queue_count,
            "result": "passed",
            "contains_plaintext_database_data": False,
        },
    )


def parser() -> argparse.ArgumentParser:
    root = argparse.ArgumentParser(description=__doc__)
    commands = root.add_subparsers(dest="command", required=True)

    manifest = commands.add_parser("manifest")
    manifest.add_argument("--input-dir", type=Path, required=True)
    manifest.add_argument("--output", type=Path, required=True)
    manifest.add_argument("--project-ref", required=True)
    manifest.add_argument("--generated-at")
    manifest.set_defaults(handler=command_manifest)

    verify = commands.add_parser("verify")
    verify.add_argument("--input-dir", type=Path, required=True)
    verify.add_argument("--manifest", type=Path, required=True)
    verify.set_defaults(handler=command_verify)

    assertions = commands.add_parser("assertions")
    assertions.add_argument("--data-sql", type=Path, required=True)
    assertions.add_argument("--output", type=Path, required=True)
    assertions.add_argument("--schema", default="public")
    assertions.set_defaults(handler=command_assertions)

    pgmq_restore = commands.add_parser("pgmq-restore")
    pgmq_restore.add_argument("--data-sql", type=Path, required=True)
    pgmq_restore.add_argument("--bootstrap-output", type=Path, required=True)
    pgmq_restore.add_argument("--finalize-output", type=Path, required=True)
    pgmq_restore.set_defaults(handler=command_pgmq_restore)

    evidence = commands.add_parser("evidence")
    evidence.add_argument("--manifest", type=Path, required=True)
    evidence.add_argument("--archive", type=Path, required=True)
    evidence.add_argument("--assertions", type=Path, required=True)
    evidence.add_argument("--pgmq-bootstrap", type=Path, required=True)
    evidence.add_argument("--pgmq-finalize", type=Path, required=True)
    evidence.add_argument("--output", type=Path, required=True)
    evidence.add_argument("--run-id", required=True)
    evidence.add_argument("--run-attempt", required=True)
    evidence.set_defaults(handler=command_evidence)
    return root


def main() -> int:
    args = parser().parse_args()
    args.handler(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
