create table notes (
  id integer generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null default ''
);

create table public_memos (
  id bigserial primary key,
  note_id bigint not null,
  user_id uuid references auth.users(id) on delete cascade,
  title text not null,
  content text,
  is_public boolean default true,
  unique (note_id, user_id)
);

create table teams (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  description text not null default '',
  owner_id uuid not null references auth.users(id) on delete cascade,
  invite_code text unique not null default substr(md5(random()::text), 1, 8),
  created_at timestamptz not null default now()
);

create table team_memberships (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references teams(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member' check (role in ('member', 'admin')),
  joined_at timestamptz not null default now(),
  unique (team_id, user_id)
);

create table team_shared_notes (
  id uuid primary key default gen_random_uuid(),
  team_id uuid not null references teams(id) on delete cascade,
  note_id bigint not null references notes(id) on delete cascade,
  shared_by uuid not null references auth.users(id) on delete cascade,
  shared_at timestamptz not null default now(),
  unique (team_id, note_id)
);

create table note_comments (
  id uuid primary key default gen_random_uuid(),
  note_id bigint not null references notes(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  content text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public_memos enable row level security;
alter table teams enable row level security;
alter table team_memberships enable row level security;
alter table team_shared_notes enable row level security;
alter table note_comments enable row level security;

create policy "Public memos viewable by all" on public_memos for select
  using (is_public = true or auth.uid() = user_id);
create policy "Users can insert own public memos" on public_memos for insert
  with check (auth.uid() = user_id);
create policy "Users can update own public memos" on public_memos for update
  using (auth.uid() = user_id);
create policy "Users can delete own public memos" on public_memos for delete
  using (auth.uid() = user_id);

create policy "team_memberships_select" on team_memberships for select
  using (user_id = auth.uid());
create policy "team_memberships_insert" on team_memberships for insert
  with check (user_id = auth.uid());
create policy "team_memberships_delete" on team_memberships for delete
  using (user_id = auth.uid());
create policy "teams_select" on teams for select
  using (
    owner_id = auth.uid()
    or exists (
      select 1 from team_memberships tm
      where tm.team_id = teams.id and tm.user_id = auth.uid()
    )
  );
create policy "teams_insert" on teams for insert with check (owner_id = auth.uid());
create policy "teams_update" on teams for update using (owner_id = auth.uid());
create policy "teams_delete" on teams for delete using (owner_id = auth.uid());
create policy "team_shared_notes_select" on team_shared_notes for select
  using (shared_by = auth.uid());
create policy "team_shared_notes_insert" on team_shared_notes for insert
  with check (shared_by = auth.uid());
create policy "team_shared_notes_delete" on team_shared_notes for delete
  using (shared_by = auth.uid());

create policy "Comments on public notes are viewable by everyone"
  on note_comments for select using (true);
create policy "Users can create comments"
  on note_comments for insert with check (auth.uid() = user_id);
create policy "Users can update their own comments"
  on note_comments for update using (auth.uid() = user_id);
create policy "Users can delete their own comments"
  on note_comments for delete using (auth.uid() = user_id);
create policy "Users can view own note comments"
  on note_comments for select using (auth.uid() = user_id);
create policy "Users can insert own note comments"
  on note_comments for insert with check (auth.uid() = user_id);
create policy "Users can update own note comments"
  on note_comments for update using (auth.uid() = user_id)
  with check (auth.uid() = user_id);
create policy "Users can delete own note comments"
  on note_comments for delete using (auth.uid() = user_id);

create view note_comment_counts as
select note_id, count(*) as comments_count from note_comments group by note_id;

grant all privileges on table notes, public_memos, teams, team_memberships,
  team_shared_notes, note_comments, note_comment_counts
to anon, authenticated, service_role;
grant usage, select on all sequences in schema public
to anon, authenticated, service_role;
