-- PS版#3 Session 11: Decart — リアルタイム生成動画 AI ($3.1B valuation)
INSERT INTO ai_university_content (provider, category, title, content, published_at)
VALUES
(
  'decart',
  'overview',
  'Decart — 世界初のリアルタイム動画生成 AI ($3.1B 評価額)',
  E'## Decart とは\n\nDecart は 2023 年設立のイスラエル発 AI スタートアップ。\n**世界初のリアルタイム動画生成モデル「Oasis」と「Mirage」** を開発・提供している。\n\n2024 年 11 月に発表した **Oasis** (AI Minecraft) は公開 3 日で 100 万ユーザーを突破。\n続く **MirageLSD** (Live-Stream Diffusion) は **40ms 以下のレイテンシ** で\nライブ動画を別の世界観に変換できる初のモデルとして話題に。\n\n2025 年 8 月に Series B で **$100M 調達 (累計 $153M+ / 評価額 $3.1B)**。\nSequoia Capital・Benchmark・Zeev Ventures が継続出資、Aleph VC が新規参画。\n\n## 既存の動画生成 AI との違い\n\n| 観点 | Decart (Mirage/Oasis) | Runway / Luma / Kling 等 |\n|------|----------------------|---------------------------|\n| **生成方式** | リアルタイム連続生成 | 5〜10 秒バッチ生成 |\n| **レイテンシ** | <40ms (体感ゼロ) | 10 秒〜数分 |\n| **入力** | ライブ動画ストリーム | テキスト・1枚画像 |\n| **長さ制限** | 無制限 (連続変換) | 5〜10 秒/クリップ |\n| **対話性** | プレイ可能 (ゲーム化) | 単方向生成 |\n| **インフラ** | 自社 GPU 最適化スタック | 外部クラウド GPU |\n\n## 主要プロダクト\n\n### Oasis (2024-11) — AI Minecraft\n\n- **世界初の playable な AI 生成ゲーム** (Minecraft 風オープンワールド)\n- キーボード/マウス操作で世界が AI により逐次生成される\n- 公開 3 日で 100 万プレイヤー突破\n- バックエンドは独自学習の World Model + GPU 最適化\n\n### MirageLSD (2025-夏) — リアルタイム動画変換\n\n- **Live-Stream Diffusion**: ライブ動画を別の絵柄/世界観に変換\n- レイテンシ <40ms (人間の知覚閾値以下)\n- 入力: Webcam・OBS・録画動画\n- 出力: アニメ調・サイバーパンク・写実油絵 など任意のスタイル\n- 用途: ライブ配信エフェクト・バーチャル背景・XR コンテンツ\n\n## ビジネスモデル\n\n- **Mirage API** (近日公開予定): 動画変換を SaaS として提供\n- **GPU アクセラレーションスタック**: 自社最適化技術を他社にライセンス\n- **エンタープライズ契約**: ゲームスタジオ・配信プラットフォーム向け\n\n## 創業・組織\n\n- 設立: 2023 年 (テルアビブ + サンフランシスコ)\n- 共同創業者: Dean Leitersdorf (CEO)、Moshe Shalev (CPO)\n- 強み: GPU カーネル最適化 + 世界モデル研究の融合',
  '2026-04-20'
),
(
  'decart',
  'models',
  'Decart モデル一覧 (Oasis / MirageLSD)',
  E'## モデル比較\n\n| モデル | リリース | 入力 | 出力 | レイテンシ | ステータス |\n|--------|---------|------|------|-----------|-----------|\n| **Oasis** | 2024-11 | キー入力 | ゲーム映像 | リアルタイム | 公開 (Web デモ) |\n| **MirageLSD** | 2025-夏 | ライブ動画 | スタイル変換動画 | <40ms | 公開 (API 準備中) |\n| **次期 Foundation Model** | 2026 予定 | マルチモーダル | 任意 | リアルタイム | 開発中 |\n\n## Oasis 詳細\n\n```text\n概要:\n  - 世界初の playable AI 生成 Minecraft 風ゲーム\n  - 学習: 数千時間の Minecraft プレイ動画 + キー入力ペア\n\n技術:\n  - World Model (DiT 系) + Action Encoder\n  - フレーム毎に次フレームを 1.5B param モデルで予測\n  - 独自 GPU 最適化 (1 H100 で 20fps 達成)\n\nプレイ:\n  - https://oasis.decart.ai/welcome (無料・登録不要)\n  - WASD 移動・マウスで視点変更・ブロック設置\n```\n\n## MirageLSD 詳細\n\n```text\n概要:\n  - ライブ動画を任意のスタイルに連続変換\n  - 例: Webcam → アニメキャラ・実写 → ピクサー風\n\n技術:\n  - Latent Stream Diffusion (LSD) アーキテクチャ\n  - フレーム間の整合性を保ちながら逐次変換\n  - <40ms = OBS の 30fps ライブ配信に組込可\n\n対応プロンプト例:\n  - "Studio Ghibli style anime"\n  - "Cyberpunk neon city overlay"\n  - "Oil painting in Van Gogh style"\n  - "Underwater scene with bioluminescent fish"\n\nデモ:\n  - https://mirage.decart.ai/ (Web ブラウザで Webcam 接続)\n```\n\n## 自分株式会社からの活用イメージ\n\n| 機能 | Decart 適用 |\n|------|-----------|\n| **AI 大学** | プレイ可能な「AI モデル体験」コンテンツとして埋め込み |\n| **ホーム画面** | ユーザーアバター動画にスタイルエフェクト |\n| **動画編集スキル** | NotebookLM 動画 → スタイル変換 → YouTube 投稿パイプライン |\n| **ゲーミフィケーション** | 学習達成バッジを Oasis 風 3D 世界で可視化 |\n\n## 競合・近接プロバイダー\n\n- **Runway / Luma / Kling**: 短尺バッチ生成 → Decart は連続リアルタイム\n- **Pika / Hailuo**: 同上 (バッチ)\n- **NVIDIA Omniverse**: リアルタイム 3D だが AI 生成ではない',
  '2026-04-20'
),
(
  'decart',
  'api',
  'Decart 使い方 (Web デモ + 今後の API)',
  E'## 現状の利用方法 (2026-04 時点)\n\nMirage API は 2026 年内公開予定。現時点では Web デモ経由で体験可能。\n\n### Oasis (AI Minecraft) を試す\n\n```text\n1. https://oasis.decart.ai/welcome を開く\n2. 「Play Now」をクリック (登録不要)\n3. WASD 移動・マウス視点変更・左クリックでブロック設置\n4. 数十秒でセッションタイムアウト (無料デモのため)\n```\n\n### MirageLSD (動画スタイル変換) を試す\n\n```text\n1. https://mirage.decart.ai/ を開く\n2. Webcam アクセスを許可\n3. プロンプト入力 (例: "anime style")\n4. リアルタイムで変換された動画が表示される\n5. OBS の仮想カメラと組合せてライブ配信に組込可\n```\n\n## 想定 API スキーマ (公式公開時に確認)\n\n```typescript\n// supabase/functions/decart-stylize/index.ts\nimport { serve } from "https://deno.land/std@0.177.0/http/server.ts";\n\nserve(async (req) => {\n  const { videoUrl, prompt, style } = await req.json();\n\n  // Decart Mirage API (β想定)\n  const response = await fetch("https://api.decart.ai/v1/mirage/transform", {\n    method: "POST",\n    headers: {\n      "Authorization": `Bearer ${Deno.env.get("DECART_API_KEY")}`,\n      "Content-Type": "application/json",\n    },\n    body: JSON.stringify({\n      input_url: videoUrl,\n      prompt: prompt,           // 例: "Studio Ghibli style"\n      style: style,             // anime / oil_painting / cyberpunk\n      output_format: "mp4",\n      max_duration_seconds: 60,\n    }),\n  });\n\n  const result = await response.json();\n  return new Response(JSON.stringify({ outputUrl: result.url }), {\n    headers: { "Content-Type": "application/json" },\n  });\n});\n```\n\n## Flutter Web からの呼出 (公開後想定)\n\n```dart\n// lib/services/decart_service.dart\nimport \'package:supabase_flutter/supabase_flutter.dart\';\n\nclass DecartService {\n  static Future<String?> stylizeVideo({\n    required String videoUrl,\n    required String prompt,\n    String style = \'anime\',\n  }) async {\n    final supabase = Supabase.instance.client;\n    final response = await supabase.functions.invoke(\n      \'decart-stylize\',\n      body: {\n        \'videoUrl\': videoUrl,\n        \'prompt\': prompt,\n        \'style\': style,\n      },\n    );\n    return (response.data as Map?)?[\'outputUrl\'] as String?;\n  }\n}\n```\n\n## 料金 (推定 — API 公開時に確認)\n\n- **Web デモ**: 完全無料 (セッション制限あり)\n- **Mirage API β**: 招待制 (waitlist 受付中)\n- **想定価格帯**: $0.05〜0.20/秒 (リアルタイム GPU 占有のため高単価予測)\n\n## 注意事項・制約\n\n- **生成コンテンツの著作権**: モデル学習データに既存ゲーム/動画が含まれる可能性\n- **長尺保証なし**: <40ms レイテンシだが連続稼働時間は GPU 課金次第\n- **モバイル対応**: Webcam ベース → スマホブラウザでも動作 (iOS Safari は要検証)\n\n## 公式リソース\n\n- Web: https://decart.ai/\n- Mirage デモ: https://mirage.decart.ai/\n- Oasis デモ: https://oasis.decart.ai/welcome\n- Research: https://decart.ai/research\n- Mirage 解説: https://decart.ai/publications/mirage',
  '2026-04-20'
)
ON CONFLICT (provider, category) DO UPDATE SET
  title = EXCLUDED.title,
  content = EXCLUDED.content,
  published_at = EXCLUDED.published_at;
