-- Initial seed: 157 design_screens from lib/data/design_compliance_data.dart
-- 7 design_rollout overrides from lib/data/ui_improvement_rollout_data.dart


-- === design_screens seed ===
INSERT INTO design_screens (route, name, category, compliance, audit_date, notes, mcp_tool_used)
VALUES
  ('/landing', 'ランディングページ', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-04-05', '一部セクションでスペーシング要改善', NULL),
  ('/enterprise', 'エンタープライズLP', 'marketing', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-03-30', NULL, NULL),
  ('/feature-requests', '機能リクエスト', 'marketing', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/referral', 'リファラルプログラム', 'marketing', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/vs-notion', 'Notion 比較ページ', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-26', NULL, NULL),
  ('/vs-evernote', 'Evernote 比較ページ', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-26', NULL, NULL),
  ('/vs-moneyforward', 'MoneyForward 比較', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-26', NULL, NULL),
  ('/vs-slack', 'Slack 比較ページ', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-26', NULL, NULL),
  ('/vs-chatwork', 'Chatwork 比較', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-26', NULL, NULL),
  ('/vs-x', 'X (Twitter) 比較', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-26', NULL, NULL),
  ('/vs-amazon', 'Amazon 比較ページ', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-26', NULL, NULL),
  ('/vs-google', 'Google 比較ページ', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-31', NULL, NULL),
  ('/vs-discord', 'Discord 比較', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-31', NULL, NULL),
  ('/vs-line', 'LINE 比較ページ', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-31', NULL, NULL),
  ('/vs-github', 'GitHub 比較ページ', 'marketing', ARRAY[true,true,true,false,true,true,true]::boolean[], '2026-03-31', NULL, NULL),
  ('/vs-animaworks', 'Animaworks 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-claude-code', 'Claude Code 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-codex', 'Codex 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-netkeiba', 'netkeiba 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-openclaw', 'OpenClaw 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-claude-cowork', 'Claude Cowork 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-jobcan', 'ジョブカン 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-microsoft', 'Microsoft 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-facebook', 'Facebook 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/vs-liven', 'Liven 比較', 'marketing', NULL, NULL, NULL, NULL),
  ('/home', 'ホーム (メインハブ)', 'home', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-04-06', '6907行の大規模ファイル。タイポグラフィ・スペーシング要統一', NULL),
  ('/home-insights', '成長・支援ダッシュボード', 'home', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-28', NULL, NULL),
  ('/work-menu', '業務メニュー', 'home', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-28', NULL, NULL),
  ('/admin', '管理者ダッシュボード', 'home', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-03-26', NULL, NULL),
  ('/ui-design-status', 'UIデザインステータス (本ページ)', 'home', ARRAY[true,true,true,true,true,true,true]::boolean[], '2026-04-07', 'DESIGN.md に完全準拠して新規作成', NULL),
  ('/note-editor', 'ノートエディタ', 'notes', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-30', 'タイポグラフィ・スペーシング要改善', NULL),
  ('/public-memos', '公開メモ一覧', 'notes', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/tech-blog-tracker', '技術ブログ管理', 'notes', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/templates', 'テンプレート広場 (18種)', 'notes', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-03-28', NULL, NULL),
  ('/table-data', 'テーブルDB (Notion Database相当)', 'notes', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-03-28', NULL, NULL),
  ('/kanban', 'カンバンボード', 'notes', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-03-28', NULL, NULL),
  ('/mind-map', 'マインドマップ', 'notes', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-25', 'タイポグラフィ要改善', NULL),
  ('/gantt-timeline', 'ガントチャート', 'notes', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-02', NULL, NULL),
  ('/wiki-database', 'Wikiデータベース', 'notes', NULL, NULL, NULL, NULL),
  ('/knowledge-base', 'ナレッジベース', 'notes', NULL, NULL, NULL, NULL),
  ('/note-comments', 'ノートコメント', 'notes', ARRAY[true,true,true,true,true,true,true]::boolean[], '2026-03-30', NULL, NULL),
  ('/ai-search', 'AI全文検索', 'ai', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-28', 'タイポグラフィ・スペーシング要改善', NULL),
  ('/morning-briefing', 'モーニングブリーフィング', 'ai', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/embedding-lab', 'Embedding ラボ', 'ai', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-03-31', NULL, NULL),
  ('/ai-writing-assistant', 'AI文章支援', 'ai', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-04-03', NULL, NULL),
  ('/smart-inbox', 'スマート受信トレイ', 'ai', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-04-03', NULL, NULL),
  ('/ai-secretary', 'AI秘書', 'ai', ARRAY[true,false,false,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/ai-image-generator', 'AI画像生成', 'ai', NULL, NULL, NULL, NULL),
  ('/ai-suggest-tags', 'AIタグ提案', 'ai', NULL, NULL, NULL, NULL),
  ('/workflow-automation', 'AIワークフロー自動化', 'ai', NULL, NULL, NULL, NULL),
  ('/semantic-search', 'セマンティック検索', 'ai', NULL, NULL, NULL, NULL),
  ('/growth-mission', '成長ミッション', 'business', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/growth-command-center', 'Growth 指揮センター', 'business', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/team-workspace', 'チームワークスペース', 'business', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-03-30', NULL, NULL),
  ('/local-election-700', '統一地方選 700人目標', 'business', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-31', NULL, NULL),
  ('/election-strategy', '選挙戦略ページ', 'business', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/asset-management', '資産管理', 'business', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-25', 'タイポグラフィ要改善', NULL),
  ('/cfo-office', 'CFO室', 'business', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/financial-report', '財務レポート', 'business', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/growth-achievement-summary', '成長実績サマリー', 'business', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/growth-weekly-digest', '週次グロースダイジェスト', 'business', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/crm-pipeline', 'CRM営業パイプライン', 'business', NULL, NULL, NULL, NULL),
  ('/gantt-timeline', 'ガントチャート', 'business', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-02', NULL, NULL),
  ('/daily-habits', '毎日の習慣', 'personal', ARRAY[true,false,false,false,true,true,false]::boolean[], '2026-03-20', 'カラートークン・タイポグラフィ要全面改善', NULL),
  ('/health', '健康管理', 'personal', ARRAY[true,false,false,false,true,true,false]::boolean[], '2026-03-20', '要改善', NULL),
  ('/mental-check', 'メンタルチェック', 'personal', ARRAY[true,false,false,false,true,true,false]::boolean[], '2026-03-20', '要改善', NULL),
  ('/memory-drill', '記憶ドリル', 'personal', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-25', 'タイポグラフィ要改善', NULL),
  ('/calendar-events', 'カレンダー (TableCalendar)', 'personal', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-06', NULL, NULL),
  ('/habit-gamification', '習慣ゲーミフィケーション', 'personal', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-03', NULL, NULL),
  ('/behavior-review', '行動振り返り', 'personal', ARRAY[true,false,false,false,true,true,false]::boolean[], '2026-03-20', NULL, NULL),
  ('/expense-tracker', '支出トラッカー', 'personal', ARRAY[true,false,false,false,false,true,false]::boolean[], '2026-03-20', NULL, NULL),
  ('/shopping-list', '買い物リスト', 'personal', ARRAY[true,false,false,false,false,true,false]::boolean[], '2026-03-20', NULL, NULL),
  ('/wip-limit', 'WIP制限管理', 'personal', NULL, NULL, NULL, NULL),
  ('/travel-itinerary', '旅行プランナー', 'personal', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-03', NULL, NULL),
  ('/recipe-meal-planner', 'レシピ・献立プランナー', 'personal', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-03', NULL, NULL),
  ('/focus-timer', 'フォーカスタイマー', 'personal', NULL, NULL, NULL, NULL),
  ('/goal-tracker', '目標トラッカー', 'personal', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/guitar-recording-studio', 'ギタースタジオ', 'creative', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-05', NULL, NULL),
  ('/public-guitar-gallery', '公開ギャラリー', 'creative', ARRAY[true,true,true,true,true,true,true]::boolean[], '2026-04-06', 'DESIGN.md に完全準拠', NULL),
  ('/code-playground', 'コードプレイグラウンド', 'creative', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-03', NULL, NULL),
  ('/virtual-whiteboard', 'バーチャルホワイトボード', 'creative', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-03', NULL, NULL),
  ('/music-collaboration', '音楽コラボ', 'creative', NULL, NULL, NULL, NULL),
  ('/music-playlist-manager', '音楽プレイリスト管理', 'creative', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/ai-image-generator', 'AI画像生成', 'creative', NULL, NULL, NULL, NULL),
  ('/viral-ad-generator', 'バイラル広告生成', 'creative', NULL, NULL, NULL, NULL),
  ('/video-ad-generator', '動画広告生成', 'creative', NULL, NULL, NULL, NULL),
  ('/edge-functions', 'Edge Function 一覧', 'admin', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/ai-status', 'AI ステータス', 'admin', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-03-25', NULL, NULL),
  ('/analytics-export', '分析エクスポート', 'admin', ARRAY[true,true,true,false,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/settings', '設定', 'admin', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-20', 'タイポグラフィ・スペーシング要改善', NULL),
  ('/api-playground', 'APIプレイグラウンド', 'admin', NULL, NULL, NULL, NULL),
  ('/feature-flags', 'フィーチャーフラグ', 'admin', NULL, NULL, NULL, NULL),
  ('/profile-settings', 'プロフィール設定', 'admin', ARRAY[true,true,false,false,true,true,false]::boolean[], '2026-03-26', NULL, NULL),
  ('/agents', 'AI エージェント組織', 'ai', NULL, NULL, NULL, NULL),
  ('/danshari', '断捨離ガイド', 'personal', NULL, NULL, NULL, NULL),
  ('/real-world-danshari', 'リアル断捨離', 'personal', NULL, NULL, NULL, NULL),
  ('/stock-tasks', '週末ストックタスク', 'personal', NULL, NULL, NULL, NULL),
  ('/mindless-task', '思考停止タスク', 'personal', NULL, NULL, NULL, NULL),
  ('/thought-capture', '思考キャプチャ', 'personal', NULL, NULL, NULL, NULL),
  ('/thought-anchor', 'アンカー思考', 'personal', NULL, NULL, NULL, NULL),
  ('/reality-check', 'リアリティチェック', 'personal', NULL, NULL, NULL, NULL),
  ('/stats', '統計・分析', 'admin', NULL, NULL, NULL, NULL),
  ('/activity-feed', 'アクティビティフィード', 'notes', NULL, NULL, NULL, NULL),
  ('/social-feed', 'ソーシャルフィード', 'notes', NULL, NULL, NULL, NULL),
  ('/news-rss', 'ニュース・RSSアグリゲーター', 'ai', NULL, NULL, NULL, NULL),
  ('/booking-sync', 'ブッキング同期', 'business', NULL, NULL, NULL, NULL),
  ('/horse-racing', '競馬予測 AI', 'ai', NULL, NULL, NULL, NULL),
  ('/language-learning', '語学学習', 'ai', NULL, NULL, NULL, NULL),
  ('/horse-racing', '競馬予測', 'ai', NULL, NULL, NULL, NULL),
  ('/fitness-health-tracker', 'フィットネス・健康トラッカー', 'personal', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/legal-compliance', '法務・コンプライアンス', 'business', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/elearning', 'eラーニング', 'ai', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/event-ticketing', 'イベントチケット管理', 'business', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/form-builder', 'フォームビルダー', 'admin', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/home-iot', 'ホームIoT管理', 'personal', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/real-estate', '不動産管理', 'business', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-03', NULL, NULL),
  ('/budget-financial-planner', '予算・財務プランナー', 'business', NULL, NULL, NULL, NULL),
  ('/appointment-scheduler', '予約スケジューラー', 'business', NULL, NULL, NULL, NULL),
  ('/subscription-billing', 'サブスクリプション管理', 'business', NULL, NULL, NULL, NULL),
  ('/vehicle-fleet', '車両フリート管理', 'business', NULL, NULL, NULL, NULL),
  ('/spreadsheet-database', 'スプレッドシートDB', 'notes', NULL, NULL, NULL, NULL),
  ('/qr-code-generator', 'QRコード生成', 'creative', NULL, NULL, NULL, NULL),
  ('/voice-memo', '音声メモ文字起こし', 'ai', NULL, NULL, NULL, NULL),
  ('/time-tracker', '時間トラッカー', 'personal', NULL, NULL, NULL, NULL),
  ('/changelog', 'チェンジログ', 'admin', NULL, NULL, NULL, NULL),
  ('/social-scheduler', 'SNSスケジューラー', 'marketing', NULL, NULL, NULL, NULL),
  ('/video-meeting', 'ビデオミーティング', 'business', NULL, NULL, NULL, NULL),
  ('/password-vault', 'パスワード金庫', 'admin', NULL, NULL, NULL, NULL),
  ('/two-factor-auth', '二要素認証管理', 'admin', NULL, NULL, NULL, NULL),
  ('/access-control', 'アクセス制御', 'admin', NULL, NULL, NULL, NULL),
  ('/sitemap-analytics', 'サイトマップ分析', 'admin', NULL, NULL, NULL, NULL),
  ('/photo-gallery', 'フォトギャラリー', 'creative', NULL, NULL, NULL, NULL),
  ('/podcast-manager', 'ポッドキャスト管理', 'creative', NULL, NULL, NULL, NULL),
  ('/screen-recorder', 'スクリーンレコーダー', 'creative', NULL, NULL, NULL, NULL),
  ('/auction-marketplace', 'オークションマーケット', 'business', NULL, NULL, NULL, NULL),
  ('/affiliate-marketing', 'アフィリエイト管理', 'marketing', NULL, NULL, NULL, NULL),
  ('/donation', '寄付管理', 'business', NULL, NULL, NULL, NULL),
  ('/emergency-contacts', '緊急連絡先', 'personal', NULL, NULL, NULL, NULL),
  ('/family-sharing', 'ファミリー共有', 'personal', NULL, NULL, NULL, NULL),
  ('/pet-care', 'ペットケア', 'personal', NULL, NULL, NULL, NULL),
  ('/carbon-footprint', 'カーボンフットプリント', 'personal', NULL, NULL, NULL, NULL),
  ('/recruitment', '採用管理', 'business', NULL, NULL, NULL, NULL),
  ('/inventory-barcode', '在庫・バーコード管理', 'business', NULL, NULL, NULL, NULL),
  ('/virtual-pet', 'バーチャルペット', 'creative', NULL, NULL, NULL, NULL),
  ('/ar-navigation', 'ARナビゲーション', 'creative', NULL, NULL, NULL, NULL),
  ('/digital-wallet', 'デジタルウォレット', 'business', NULL, NULL, NULL, NULL),
  ('/loyalty-points', 'ロイヤルティポイント', 'business', NULL, NULL, NULL, NULL),
  ('/gift-registry', 'ギフトレジストリ', 'personal', NULL, NULL, NULL, NULL),
  ('/parking-reservation', '駐車場予約', 'business', NULL, NULL, NULL, NULL),
  ('/address-book', 'アドレスブック', 'personal', NULL, NULL, NULL, NULL),
  ('/customer-feedback', '顧客フィードバック', 'business', NULL, NULL, NULL, NULL),
  ('/reading-list', '読書リスト', 'personal', NULL, NULL, NULL, NULL),
  ('/bookmark-sync', 'ブックマーク同期', 'personal', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/wardrobe', 'ワードローブ管理', 'personal', NULL, NULL, NULL, NULL),
  ('/document-esignature', '電子署名', 'business', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/meeting-manager', 'ミーティング管理', 'business', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL),
  ('/ci-cd-pipeline', 'CI/CDパイプライン管理', 'admin', ARRAY[true,true,true,true,true,true,false]::boolean[], '2026-04-04', NULL, NULL)
ON CONFLICT (route) DO NOTHING;

-- === design_rollout seed ===
INSERT INTO design_rollout (route, stage, figma_mcp, ai_designer, design_skills, design_md, headline, next_step)
VALUES
  ('/ui-design-status', 'applied', 'applied', 'applied', 'applied', 'applied', 'Screen inventory, rollout state, and audit score are visible on the site.', 'Expand the same workflow to more screen groups and keep the inventory current.'),
  ('/work-menu', 'applied', 'applied', 'applied', 'applied', 'applied', 'The main navigation now includes a direct entry to the rollout dashboard.', 'Add stronger priority indicators by section.'),
  ('/guitar-recording-studio', 'applied', 'applied', 'applied', 'applied', 'applied', 'The recording studio is treated as a primary screen in the new UI workflow.', 'Keep refining history cards and the AI feedback flow.'),
  ('/public-guitar-gallery', 'in_progress', 'in_progress', 'applied', 'applied', 'applied', 'The public gallery is being aligned with the upgraded recording flow.', 'Tighten density and sharing UX with a Figma-backed pass.'),
  ('/landing', 'in_progress', 'applied', 'in_progress', 'applied', 'applied', 'The landing experience follows the new direction and is still being tuned.', 'Refine hero density and comparison flow.'),
  ('/home', 'in_progress', 'in_progress', 'in_progress', 'applied', 'applied', 'The home screen now benefits from the shared theme refresh and is being reorganized.', 'Improve card priority and reduce cognitive load.'),
  ('/enterprise', 'in_progress', 'in_progress', 'planned', 'applied', 'applied', 'Enterprise-facing marketing screens are already on the rollout track.', 'Run a stronger Figma pass shared with the comparison pages.')
ON CONFLICT (route) DO NOTHING;
