-- PS#4 S60: competitor_features Phase 2 Batch 3 — chat(7) + fintech(13) + cloud-office(5) + developer-tools(6) = 31社

INSERT INTO public.competitor_features
  (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status)
VALUES
-- ================================================================
-- chat (7社)
-- ================================================================
-- bluesky (decentralized social / AT Protocol)
('bluesky', 'notes',               'ノート・メモ',         false, 'done'),
('bluesky', 'task_management',     'タスク管理',           false, 'done'),
('bluesky', 'calendar',            'カレンダー',           false, 'notYet'),
('bluesky', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('bluesky', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('bluesky', 'messaging',           'メッセージ・チャット', true,  'done'),
('bluesky', 'social_sharing',      'SNS・シェア',          true,  'partial'),
('bluesky', 'code_assistant',      'コード補助',           false, 'notYet'),
('bluesky', 'document_management', 'ドキュメント管理',     false, 'partial'),
('bluesky', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- signal (encrypted messaging)
('signal', 'notes',               'ノート・メモ',         false, 'done'),
('signal', 'task_management',     'タスク管理',           false, 'done'),
('signal', 'calendar',            'カレンダー',           false, 'notYet'),
('signal', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('signal', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('signal', 'messaging',           'メッセージ・チャット', true,  'done'),
('signal', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('signal', 'code_assistant',      'コード補助',           false, 'notYet'),
('signal', 'document_management', 'ドキュメント管理',     false, 'partial'),
('signal', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- teams (Microsoft Teams)
('teams', 'notes',               'ノート・メモ',         true,  'done'),
('teams', 'task_management',     'タスク管理',           true,  'done'),
('teams', 'calendar',            'カレンダー',           true,  'notYet'),
('teams', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('teams', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('teams', 'messaging',           'メッセージ・チャット', true,  'done'),
('teams', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('teams', 'code_assistant',      'コード補助',           true,  'notYet'),
('teams', 'document_management', 'ドキュメント管理',     true,  'partial'),
('teams', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- telegram (messaging + mini apps)
('telegram', 'notes',               'ノート・メモ',         false, 'done'),
('telegram', 'task_management',     'タスク管理',           true,  'done'),
('telegram', 'calendar',            'カレンダー',           false, 'notYet'),
('telegram', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('telegram', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('telegram', 'messaging',           'メッセージ・チャット', true,  'done'),
('telegram', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('telegram', 'code_assistant',      'コード補助',           false, 'notYet'),
('telegram', 'document_management', 'ドキュメント管理',     false, 'partial'),
('telegram', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- threads (Meta threads / Twitter-like)
('threads', 'notes',               'ノート・メモ',         false, 'done'),
('threads', 'task_management',     'タスク管理',           false, 'done'),
('threads', 'calendar',            'カレンダー',           false, 'notYet'),
('threads', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('threads', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('threads', 'messaging',           'メッセージ・チャット', true,  'done'),
('threads', 'social_sharing',      'SNS・シェア',          true,  'partial'),
('threads', 'code_assistant',      'コード補助',           false, 'notYet'),
('threads', 'document_management', 'ドキュメント管理',     false, 'partial'),
('threads', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- whatsapp (Meta messaging)
('whatsapp', 'notes',               'ノート・メモ',         false, 'done'),
('whatsapp', 'task_management',     'タスク管理',           false, 'done'),
('whatsapp', 'calendar',            'カレンダー',           false, 'notYet'),
('whatsapp', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('whatsapp', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('whatsapp', 'messaging',           'メッセージ・チャット', true,  'done'),
('whatsapp', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('whatsapp', 'code_assistant',      'コード補助',           false, 'notYet'),
('whatsapp', 'document_management', 'ドキュメント管理',     false, 'partial'),
('whatsapp', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- zoom (video conferencing + AI)
('zoom', 'notes',               'ノート・メモ',         false, 'done'),
('zoom', 'task_management',     'タスク管理',           true,  'done'),
('zoom', 'calendar',            'カレンダー',           true,  'notYet'),
('zoom', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('zoom', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('zoom', 'messaging',           'メッセージ・チャット', true,  'done'),
('zoom', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('zoom', 'code_assistant',      'コード補助',           false, 'notYet'),
('zoom', 'document_management', 'ドキュメント管理',     false, 'partial'),
('zoom', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- ================================================================
-- fintech (13社)
-- ================================================================
-- coincheck (crypto exchange Japan)
('coincheck', 'notes',               'ノート・メモ',         false, 'done'),
('coincheck', 'task_management',     'タスク管理',           false, 'done'),
('coincheck', 'calendar',            'カレンダー',           false, 'notYet'),
('coincheck', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('coincheck', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('coincheck', 'messaging',           'メッセージ・チャット', false, 'done'),
('coincheck', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('coincheck', 'code_assistant',      'コード補助',           false, 'notYet'),
('coincheck', 'document_management', 'ドキュメント管理',     false, 'partial'),
('coincheck', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- freee (JP cloud accounting)
('freee', 'notes',               'ノート・メモ',         false, 'done'),
('freee', 'task_management',     'タスク管理',           true,  'done'),
('freee', 'calendar',            'カレンダー',           true,  'notYet'),
('freee', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('freee', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('freee', 'messaging',           'メッセージ・チャット', false, 'done'),
('freee', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('freee', 'code_assistant',      'コード補助',           false, 'notYet'),
('freee', 'document_management', 'ドキュメント管理',     true,  'partial'),
('freee', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- freee-insurance (justInCase JP insurance)
('freee-insurance', 'notes',               'ノート・メモ',         false, 'done'),
('freee-insurance', 'task_management',     'タスク管理',           false, 'done'),
('freee-insurance', 'calendar',            'カレンダー',           false, 'notYet'),
('freee-insurance', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('freee-insurance', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('freee-insurance', 'messaging',           'メッセージ・チャット', false, 'done'),
('freee-insurance', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('freee-insurance', 'code_assistant',      'コード補助',           false, 'notYet'),
('freee-insurance', 'document_management', 'ドキュメント管理',     false, 'partial'),
('freee-insurance', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- klarna-ai (BNPL + AI checkout)
('klarna-ai', 'notes',               'ノート・メモ',         false, 'done'),
('klarna-ai', 'task_management',     'タスク管理',           false, 'done'),
('klarna-ai', 'calendar',            'カレンダー',           false, 'notYet'),
('klarna-ai', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('klarna-ai', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('klarna-ai', 'messaging',           'メッセージ・チャット', false, 'done'),
('klarna-ai', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('klarna-ai', 'code_assistant',      'コード補助',           false, 'notYet'),
('klarna-ai', 'document_management', 'ドキュメント管理',     false, 'partial'),
('klarna-ai', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- lifenet-insurance (JP life insurance)
('lifenet-insurance', 'notes',               'ノート・メモ',         false, 'done'),
('lifenet-insurance', 'task_management',     'タスク管理',           false, 'done'),
('lifenet-insurance', 'calendar',            'カレンダー',           false, 'notYet'),
('lifenet-insurance', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('lifenet-insurance', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('lifenet-insurance', 'messaging',           'メッセージ・チャット', false, 'done'),
('lifenet-insurance', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('lifenet-insurance', 'code_assistant',      'コード補助',           false, 'notYet'),
('lifenet-insurance', 'document_management', 'ドキュメント管理',     false, 'partial'),
('lifenet-insurance', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- metamask (Web3 wallet)
('metamask', 'notes',               'ノート・メモ',         false, 'done'),
('metamask', 'task_management',     'タスク管理',           false, 'done'),
('metamask', 'calendar',            'カレンダー',           false, 'notYet'),
('metamask', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('metamask', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('metamask', 'messaging',           'メッセージ・チャット', false, 'done'),
('metamask', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('metamask', 'code_assistant',      'コード補助',           false, 'notYet'),
('metamask', 'document_management', 'ドキュメント管理',     false, 'partial'),
('metamask', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- money-tree (JP personal finance aggregator)
('money-tree', 'notes',               'ノート・メモ',         false, 'done'),
('money-tree', 'task_management',     'タスク管理',           false, 'done'),
('money-tree', 'calendar',            'カレンダー',           false, 'notYet'),
('money-tree', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('money-tree', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('money-tree', 'messaging',           'メッセージ・チャット', false, 'done'),
('money-tree', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('money-tree', 'code_assistant',      'コード補助',           false, 'notYet'),
('money-tree', 'document_management', 'ドキュメント管理',     false, 'partial'),
('money-tree', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- moneyforward-cloud (MF クラウド経費/請求)
('moneyforward-cloud', 'notes',               'ノート・メモ',         false, 'done'),
('moneyforward-cloud', 'task_management',     'タスク管理',           true,  'done'),
('moneyforward-cloud', 'calendar',            'カレンダー',           false, 'notYet'),
('moneyforward-cloud', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('moneyforward-cloud', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('moneyforward-cloud', 'messaging',           'メッセージ・チャット', false, 'done'),
('moneyforward-cloud', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('moneyforward-cloud', 'code_assistant',      'コード補助',           false, 'notYet'),
('moneyforward-cloud', 'document_management', 'ドキュメント管理',     true,  'partial'),
('moneyforward-cloud', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- paidy (JP BNPL)
('paidy', 'notes',               'ノート・メモ',         false, 'done'),
('paidy', 'task_management',     'タスク管理',           false, 'done'),
('paidy', 'calendar',            'カレンダー',           false, 'notYet'),
('paidy', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('paidy', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('paidy', 'messaging',           'メッセージ・チャット', false, 'done'),
('paidy', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('paidy', 'code_assistant',      'コード補助',           false, 'notYet'),
('paidy', 'document_management', 'ドキュメント管理',     false, 'partial'),
('paidy', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- paypal (global payments)
('paypal', 'notes',               'ノート・メモ',         false, 'done'),
('paypal', 'task_management',     'タスク管理',           false, 'done'),
('paypal', 'calendar',            'カレンダー',           false, 'notYet'),
('paypal', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('paypal', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('paypal', 'messaging',           'メッセージ・チャット', true,  'done'),
('paypal', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('paypal', 'code_assistant',      'コード補助',           false, 'notYet'),
('paypal', 'document_management', 'ドキュメント管理',     false, 'partial'),
('paypal', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- stripe (developer payments platform)
('stripe', 'notes',               'ノート・メモ',         false, 'done'),
('stripe', 'task_management',     'タスク管理',           true,  'done'),
('stripe', 'calendar',            'カレンダー',           false, 'notYet'),
('stripe', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('stripe', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('stripe', 'messaging',           'メッセージ・チャット', false, 'done'),
('stripe', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('stripe', 'code_assistant',      'コード補助',           true,  'notYet'),
('stripe', 'document_management', 'ドキュメント管理',     true,  'partial'),
('stripe', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- wise (international money transfer)
('wise', 'notes',               'ノート・メモ',         false, 'done'),
('wise', 'task_management',     'タスク管理',           false, 'done'),
('wise', 'calendar',            'カレンダー',           false, 'notYet'),
('wise', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('wise', 'ai_assistant',        'AIアシスタント',       false, 'done'),
('wise', 'messaging',           'メッセージ・チャット', true,  'done'),
('wise', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('wise', 'code_assistant',      'コード補助',           false, 'notYet'),
('wise', 'document_management', 'ドキュメント管理',     false, 'partial'),
('wise', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- yayoi (JP accounting software)
('yayoi', 'notes',               'ノート・メモ',         false, 'done'),
('yayoi', 'task_management',     'タスク管理',           true,  'done'),
('yayoi', 'calendar',            'カレンダー',           false, 'notYet'),
('yayoi', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('yayoi', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('yayoi', 'messaging',           'メッセージ・チャット', false, 'done'),
('yayoi', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('yayoi', 'code_assistant',      'コード補助',           false, 'notYet'),
('yayoi', 'document_management', 'ドキュメント管理',     true,  'partial'),
('yayoi', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- ================================================================
-- cloud-office (5社)
-- ================================================================
-- atlassian (Jira / Confluence / Trello)
('atlassian', 'notes',               'ノート・メモ',         true,  'done'),
('atlassian', 'task_management',     'タスク管理',           true,  'done'),
('atlassian', 'calendar',            'カレンダー',           true,  'notYet'),
('atlassian', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('atlassian', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('atlassian', 'messaging',           'メッセージ・チャット', true,  'done'),
('atlassian', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('atlassian', 'code_assistant',      'コード補助',           true,  'notYet'),
('atlassian', 'document_management', 'ドキュメント管理',     true,  'partial'),
('atlassian', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- dropbox (cloud file storage)
('dropbox', 'notes',               'ノート・メモ',         false, 'done'),
('dropbox', 'task_management',     'タスク管理',           false, 'done'),
('dropbox', 'calendar',            'カレンダー',           false, 'notYet'),
('dropbox', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('dropbox', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('dropbox', 'messaging',           'メッセージ・チャット', false, 'done'),
('dropbox', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('dropbox', 'code_assistant',      'コード補助',           false, 'notYet'),
('dropbox', 'document_management', 'ドキュメント管理',     true,  'partial'),
('dropbox', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- twilio (cloud communications API)
('twilio', 'notes',               'ノート・メモ',         false, 'done'),
('twilio', 'task_management',     'タスク管理',           false, 'done'),
('twilio', 'calendar',            'カレンダー',           false, 'notYet'),
('twilio', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('twilio', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('twilio', 'messaging',           'メッセージ・チャット', true,  'done'),
('twilio', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('twilio', 'code_assistant',      'コード補助',           true,  'notYet'),
('twilio', 'document_management', 'ドキュメント管理',     false, 'partial'),
('twilio', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- vercel (front-end cloud)
('vercel', 'notes',               'ノート・メモ',         false, 'done'),
('vercel', 'task_management',     'タスク管理',           false, 'done'),
('vercel', 'calendar',            'カレンダー',           false, 'notYet'),
('vercel', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('vercel', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('vercel', 'messaging',           'メッセージ・チャット', false, 'done'),
('vercel', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('vercel', 'code_assistant',      'コード補助',           true,  'notYet'),
('vercel', 'document_management', 'ドキュメント管理',     false, 'partial'),
('vercel', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- zoho (Zoho suite - separate from zoho-crm)
('zoho', 'notes',               'ノート・メモ',         true,  'done'),
('zoho', 'task_management',     'タスク管理',           true,  'done'),
('zoho', 'calendar',            'カレンダー',           true,  'notYet'),
('zoho', 'finance_tracking',    '家計・財務管理',       true,  'done'),
('zoho', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('zoho', 'messaging',           'メッセージ・チャット', true,  'done'),
('zoho', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('zoho', 'code_assistant',      'コード補助',           false, 'notYet'),
('zoho', 'document_management', 'ドキュメント管理',     true,  'partial'),
('zoho', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- ================================================================
-- developer-tools (6社)
-- ================================================================
-- datadog (cloud monitoring / APM)
('datadog', 'notes',               'ノート・メモ',         false, 'done'),
('datadog', 'task_management',     'タスク管理',           false, 'done'),
('datadog', 'calendar',            'カレンダー',           false, 'notYet'),
('datadog', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('datadog', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('datadog', 'messaging',           'メッセージ・チャット', true,  'done'),
('datadog', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('datadog', 'code_assistant',      'コード補助',           true,  'notYet'),
('datadog', 'document_management', 'ドキュメント管理',     true,  'partial'),
('datadog', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- drata (compliance automation)
('drata', 'notes',               'ノート・メモ',         false, 'done'),
('drata', 'task_management',     'タスク管理',           true,  'done'),
('drata', 'calendar',            'カレンダー',           false, 'notYet'),
('drata', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('drata', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('drata', 'messaging',           'メッセージ・チャット', false, 'done'),
('drata', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('drata', 'code_assistant',      'コード補助',           false, 'notYet'),
('drata', 'document_management', 'ドキュメント管理',     true,  'partial'),
('drata', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- pipedream (workflow automation for devs)
('pipedream', 'notes',               'ノート・メモ',         false, 'done'),
('pipedream', 'task_management',     'タスク管理',           true,  'done'),
('pipedream', 'calendar',            'カレンダー',           false, 'notYet'),
('pipedream', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('pipedream', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('pipedream', 'messaging',           'メッセージ・チャット', true,  'done'),
('pipedream', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('pipedream', 'code_assistant',      'コード補助',           true,  'notYet'),
('pipedream', 'document_management', 'ドキュメント管理',     false, 'partial'),
('pipedream', 'collaboration',       'チームコラボ',         false, 'notYet'),
-- postman (API development platform)
('postman', 'notes',               'ノート・メモ',         false, 'done'),
('postman', 'task_management',     'タスク管理',           false, 'done'),
('postman', 'calendar',            'カレンダー',           false, 'notYet'),
('postman', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('postman', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('postman', 'messaging',           'メッセージ・チャット', false, 'done'),
('postman', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('postman', 'code_assistant',      'コード補助',           true,  'notYet'),
('postman', 'document_management', 'ドキュメント管理',     true,  'partial'),
('postman', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- sentry (error monitoring)
('sentry', 'notes',               'ノート・メモ',         false, 'done'),
('sentry', 'task_management',     'タスク管理',           true,  'done'),
('sentry', 'calendar',            'カレンダー',           false, 'notYet'),
('sentry', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('sentry', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('sentry', 'messaging',           'メッセージ・チャット', true,  'done'),
('sentry', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('sentry', 'code_assistant',      'コード補助',           true,  'notYet'),
('sentry', 'document_management', 'ドキュメント管理',     false, 'partial'),
('sentry', 'collaboration',       'チームコラボ',         true,  'notYet'),
-- vanta (security compliance)
('vanta', 'notes',               'ノート・メモ',         false, 'done'),
('vanta', 'task_management',     'タスク管理',           true,  'done'),
('vanta', 'calendar',            'カレンダー',           false, 'notYet'),
('vanta', 'finance_tracking',    '家計・財務管理',       false, 'done'),
('vanta', 'ai_assistant',        'AIアシスタント',       true,  'done'),
('vanta', 'messaging',           'メッセージ・チャット', false, 'done'),
('vanta', 'social_sharing',      'SNS・シェア',          false, 'partial'),
('vanta', 'code_assistant',      'コード補助',           false, 'notYet'),
('vanta', 'document_management', 'ドキュメント管理',     true,  'partial'),
('vanta', 'collaboration',       'チームコラボ',         true,  'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature     = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status    = EXCLUDED.jibun_status,
  updated_at      = now();

INSERT INTO development_achievements (title, description, completed_at)
VALUES (
  'competitor_features Phase 2 Batch 3 — comms/fintech/cloud/dev 31社',
  'PS#4 S60。chat(7社)+fintech(13社)+cloud-office(5社)+developer-tools(6社) = 31社 × 10機能 = 310行 seed。bluesky/signal/teams/telegram/threads/whatsapp/zoom/coincheck/freee/klarna-ai/lifenet/metamask/money-tree/moneyforward-cloud/paidy/paypal/stripe/wise/yayoi/atlassian/dropbox/twilio/vercel/zoho/datadog/drata/pipedream/postman/sentry/vanta',
  '2026-04-26'
)
ON CONFLICT DO NOTHING;
