-- competitor_features Phase 2 Batch 4: entertainment/health/hr-attendance/media/e-commerce/education/legal-tech/logistics/telecom/advertising/gov-tech/mobility/real-estate/travel/food-delivery (58社)
-- PS#4 S60 2026-04-26

-- entertainment (8社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('epic-games','notes','ノート・メモ',false,'done'),
('epic-games','task_management','タスク管理',false,'done'),
('epic-games','calendar','カレンダー',false,'notYet'),
('epic-games','finance_tracking','家計・資産管理',false,'done'),
('epic-games','ai_assistant','AIアシスタント',true,'done'),
('epic-games','messaging','メッセージ',true,'done'),
('epic-games','social_sharing','SNS・ソーシャル共有',true,'partial'),
('epic-games','code_assistant','コーディング支援',true,'notYet'),
('epic-games','document_management','ドキュメント管理',false,'partial'),
('epic-games','collaboration','コラボレーション',false,'notYet'),
('netflix','notes','ノート・メモ',false,'done'),
('netflix','task_management','タスク管理',false,'done'),
('netflix','calendar','カレンダー',false,'notYet'),
('netflix','finance_tracking','家計・資産管理',false,'done'),
('netflix','ai_assistant','AIアシスタント',true,'done'),
('netflix','messaging','メッセージ',false,'done'),
('netflix','social_sharing','SNS・ソーシャル共有',true,'partial'),
('netflix','code_assistant','コーディング支援',false,'notYet'),
('netflix','document_management','ドキュメント管理',false,'partial'),
('netflix','collaboration','コラボレーション',false,'notYet'),
('nintendo','notes','ノート・メモ',false,'done'),
('nintendo','task_management','タスク管理',false,'done'),
('nintendo','calendar','カレンダー',false,'notYet'),
('nintendo','finance_tracking','家計・資産管理',false,'done'),
('nintendo','ai_assistant','AIアシスタント',false,'done'),
('nintendo','messaging','メッセージ',true,'done'),
('nintendo','social_sharing','SNS・ソーシャル共有',true,'partial'),
('nintendo','code_assistant','コーディング支援',false,'notYet'),
('nintendo','document_management','ドキュメント管理',false,'partial'),
('nintendo','collaboration','コラボレーション',false,'notYet'),
('nvidia-geforce-now','notes','ノート・メモ',false,'done'),
('nvidia-geforce-now','task_management','タスク管理',false,'done'),
('nvidia-geforce-now','calendar','カレンダー',false,'notYet'),
('nvidia-geforce-now','finance_tracking','家計・資産管理',false,'done'),
('nvidia-geforce-now','ai_assistant','AIアシスタント',true,'done'),
('nvidia-geforce-now','messaging','メッセージ',false,'done'),
('nvidia-geforce-now','social_sharing','SNS・ソーシャル共有',false,'partial'),
('nvidia-geforce-now','code_assistant','コーディング支援',false,'notYet'),
('nvidia-geforce-now','document_management','ドキュメント管理',false,'partial'),
('nvidia-geforce-now','collaboration','コラボレーション',false,'notYet'),
('roblox','notes','ノート・メモ',false,'done'),
('roblox','task_management','タスク管理',false,'done'),
('roblox','calendar','カレンダー',false,'notYet'),
('roblox','finance_tracking','家計・資産管理',false,'done'),
('roblox','ai_assistant','AIアシスタント',true,'done'),
('roblox','messaging','メッセージ',true,'done'),
('roblox','social_sharing','SNS・ソーシャル共有',true,'partial'),
('roblox','code_assistant','コーディング支援',true,'notYet'),
('roblox','document_management','ドキュメント管理',false,'partial'),
('roblox','collaboration','コラボレーション',true,'notYet'),
('sony-playstation','notes','ノート・メモ',false,'done'),
('sony-playstation','task_management','タスク管理',false,'done'),
('sony-playstation','calendar','カレンダー',false,'notYet'),
('sony-playstation','finance_tracking','家計・資産管理',false,'done'),
('sony-playstation','ai_assistant','AIアシスタント',true,'done'),
('sony-playstation','messaging','メッセージ',true,'done'),
('sony-playstation','social_sharing','SNS・ソーシャル共有',true,'partial'),
('sony-playstation','code_assistant','コーディング支援',false,'notYet'),
('sony-playstation','document_management','ドキュメント管理',false,'partial'),
('sony-playstation','collaboration','コラボレーション',false,'notYet'),
('spotify','notes','ノート・メモ',false,'done'),
('spotify','task_management','タスク管理',false,'done'),
('spotify','calendar','カレンダー',false,'notYet'),
('spotify','finance_tracking','家計・資産管理',false,'done'),
('spotify','ai_assistant','AIアシスタント',true,'done'),
('spotify','messaging','メッセージ',false,'done'),
('spotify','social_sharing','SNS・ソーシャル共有',true,'partial'),
('spotify','code_assistant','コーディング支援',false,'notYet'),
('spotify','document_management','ドキュメント管理',false,'partial'),
('spotify','collaboration','コラボレーション',false,'notYet'),
('xbox-cloud-gaming','notes','ノート・メモ',false,'done'),
('xbox-cloud-gaming','task_management','タスク管理',false,'done'),
('xbox-cloud-gaming','calendar','カレンダー',false,'notYet'),
('xbox-cloud-gaming','finance_tracking','家計・資産管理',false,'done'),
('xbox-cloud-gaming','ai_assistant','AIアシスタント',true,'done'),
('xbox-cloud-gaming','messaging','メッセージ',true,'done'),
('xbox-cloud-gaming','social_sharing','SNS・ソーシャル共有',true,'partial'),
('xbox-cloud-gaming','code_assistant','コーディング支援',false,'notYet'),
('xbox-cloud-gaming','document_management','ドキュメント管理',false,'partial'),
('xbox-cloud-gaming','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- health (9社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('calm','notes','ノート・メモ',true,'done'),
('calm','task_management','タスク管理',true,'done'),
('calm','calendar','カレンダー',true,'notYet'),
('calm','finance_tracking','家計・資産管理',false,'done'),
('calm','ai_assistant','AIアシスタント',true,'done'),
('calm','messaging','メッセージ',false,'done'),
('calm','social_sharing','SNS・ソーシャル共有',false,'partial'),
('calm','code_assistant','コーディング支援',false,'notYet'),
('calm','document_management','ドキュメント管理',false,'partial'),
('calm','collaboration','コラボレーション',false,'notYet'),
('carely','notes','ノート・メモ',true,'done'),
('carely','task_management','タスク管理',true,'done'),
('carely','calendar','カレンダー',true,'notYet'),
('carely','finance_tracking','家計・資産管理',false,'done'),
('carely','ai_assistant','AIアシスタント',true,'done'),
('carely','messaging','メッセージ',true,'done'),
('carely','social_sharing','SNS・ソーシャル共有',false,'partial'),
('carely','code_assistant','コーディング支援',false,'notYet'),
('carely','document_management','ドキュメント管理',true,'partial'),
('carely','collaboration','コラボレーション',true,'notYet'),
('coursera','notes','ノート・メモ',true,'done'),
('coursera','task_management','タスク管理',false,'done'),
('coursera','calendar','カレンダー',false,'notYet'),
('coursera','finance_tracking','家計・資産管理',false,'done'),
('coursera','ai_assistant','AIアシスタント',true,'done'),
('coursera','messaging','メッセージ',false,'done'),
('coursera','social_sharing','SNS・ソーシャル共有',true,'partial'),
('coursera','code_assistant','コーディング支援',true,'notYet'),
('coursera','document_management','ドキュメント管理',true,'partial'),
('coursera','collaboration','コラボレーション',false,'notYet'),
('curon','notes','ノート・メモ',false,'done'),
('curon','task_management','タスク管理',true,'done'),
('curon','calendar','カレンダー',true,'notYet'),
('curon','finance_tracking','家計・資産管理',true,'done'),
('curon','ai_assistant','AIアシスタント',true,'done'),
('curon','messaging','メッセージ',true,'done'),
('curon','social_sharing','SNS・ソーシャル共有',false,'partial'),
('curon','code_assistant','コーディング支援',false,'notYet'),
('curon','document_management','ドキュメント管理',true,'partial'),
('curon','collaboration','コラボレーション',false,'notYet'),
('duolingo','notes','ノート・メモ',false,'done'),
('duolingo','task_management','タスク管理',true,'done'),
('duolingo','calendar','カレンダー',false,'notYet'),
('duolingo','finance_tracking','家計・資産管理',false,'done'),
('duolingo','ai_assistant','AIアシスタント',true,'done'),
('duolingo','messaging','メッセージ',false,'done'),
('duolingo','social_sharing','SNS・ソーシャル共有',true,'partial'),
('duolingo','code_assistant','コーディング支援',false,'notYet'),
('duolingo','document_management','ドキュメント管理',false,'partial'),
('duolingo','collaboration','コラボレーション',false,'notYet'),
('google-health','notes','ノート・メモ',true,'done'),
('google-health','task_management','タスク管理',false,'done'),
('google-health','calendar','カレンダー',true,'notYet'),
('google-health','finance_tracking','家計・資産管理',false,'done'),
('google-health','ai_assistant','AIアシスタント',true,'done'),
('google-health','messaging','メッセージ',false,'done'),
('google-health','social_sharing','SNS・ソーシャル共有',false,'partial'),
('google-health','code_assistant','コーディング支援',false,'notYet'),
('google-health','document_management','ドキュメント管理',true,'partial'),
('google-health','collaboration','コラボレーション',false,'notYet'),
('headspace','notes','ノート・メモ',true,'done'),
('headspace','task_management','タスク管理',true,'done'),
('headspace','calendar','カレンダー',true,'notYet'),
('headspace','finance_tracking','家計・資産管理',false,'done'),
('headspace','ai_assistant','AIアシスタント',true,'done'),
('headspace','messaging','メッセージ',false,'done'),
('headspace','social_sharing','SNS・ソーシャル共有',false,'partial'),
('headspace','code_assistant','コーディング支援',false,'notYet'),
('headspace','document_management','ドキュメント管理',false,'partial'),
('headspace','collaboration','コラボレーション',false,'notYet'),
('oura','notes','ノート・メモ',false,'done'),
('oura','task_management','タスク管理',false,'done'),
('oura','calendar','カレンダー',false,'notYet'),
('oura','finance_tracking','家計・資産管理',false,'done'),
('oura','ai_assistant','AIアシスタント',true,'done'),
('oura','messaging','メッセージ',false,'done'),
('oura','social_sharing','SNS・ソーシャル共有',false,'partial'),
('oura','code_assistant','コーディング支援',false,'notYet'),
('oura','document_management','ドキュメント管理',true,'partial'),
('oura','collaboration','コラボレーション',false,'notYet'),
('viz-ai','notes','ノート・メモ',false,'done'),
('viz-ai','task_management','タスク管理',false,'done'),
('viz-ai','calendar','カレンダー',false,'notYet'),
('viz-ai','finance_tracking','家計・資産管理',false,'done'),
('viz-ai','ai_assistant','AIアシスタント',true,'done'),
('viz-ai','messaging','メッセージ',false,'done'),
('viz-ai','social_sharing','SNS・ソーシャル共有',false,'partial'),
('viz-ai','code_assistant','コーディング支援',false,'notYet'),
('viz-ai','document_management','ドキュメント管理',true,'partial'),
('viz-ai','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- hr-attendance (4社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('freee-hr','notes','ノート・メモ',true,'done'),
('freee-hr','task_management','タスク管理',true,'done'),
('freee-hr','calendar','カレンダー',true,'notYet'),
('freee-hr','finance_tracking','家計・資産管理',true,'done'),
('freee-hr','ai_assistant','AIアシスタント',true,'done'),
('freee-hr','messaging','メッセージ',true,'done'),
('freee-hr','social_sharing','SNS・ソーシャル共有',false,'partial'),
('freee-hr','code_assistant','コーディング支援',false,'notYet'),
('freee-hr','document_management','ドキュメント管理',true,'partial'),
('freee-hr','collaboration','コラボレーション',true,'notYet'),
('kincone','notes','ノート・メモ',false,'done'),
('kincone','task_management','タスク管理',false,'done'),
('kincone','calendar','カレンダー',true,'notYet'),
('kincone','finance_tracking','家計・資産管理',true,'done'),
('kincone','ai_assistant','AIアシスタント',false,'done'),
('kincone','messaging','メッセージ',false,'done'),
('kincone','social_sharing','SNS・ソーシャル共有',false,'partial'),
('kincone','code_assistant','コーディング支援',false,'notYet'),
('kincone','document_management','ドキュメント管理',true,'partial'),
('kincone','collaboration','コラボレーション',false,'notYet'),
('kingoftime','notes','ノート・メモ',false,'done'),
('kingoftime','task_management','タスク管理',false,'done'),
('kingoftime','calendar','カレンダー',true,'notYet'),
('kingoftime','finance_tracking','家計・資産管理',true,'done'),
('kingoftime','ai_assistant','AIアシスタント',false,'done'),
('kingoftime','messaging','メッセージ',false,'done'),
('kingoftime','social_sharing','SNS・ソーシャル共有',false,'partial'),
('kingoftime','code_assistant','コーディング支援',false,'notYet'),
('kingoftime','document_management','ドキュメント管理',true,'partial'),
('kingoftime','collaboration','コラボレーション',false,'notYet'),
('smarthr','notes','ノート・メモ',true,'done'),
('smarthr','task_management','タスク管理',true,'done'),
('smarthr','calendar','カレンダー',true,'notYet'),
('smarthr','finance_tracking','家計・資産管理',true,'done'),
('smarthr','ai_assistant','AIアシスタント',true,'done'),
('smarthr','messaging','メッセージ',true,'done'),
('smarthr','social_sharing','SNS・ソーシャル共有',false,'partial'),
('smarthr','code_assistant','コーディング支援',false,'notYet'),
('smarthr','document_management','ドキュメント管理',true,'partial'),
('smarthr','collaboration','コラボレーション',true,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- media (3社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('ameba','notes','ノート・メモ',true,'done'),
('ameba','task_management','タスク管理',false,'done'),
('ameba','calendar','カレンダー',false,'notYet'),
('ameba','finance_tracking','家計・資産管理',false,'done'),
('ameba','ai_assistant','AIアシスタント',false,'done'),
('ameba','messaging','メッセージ',true,'done'),
('ameba','social_sharing','SNS・ソーシャル共有',true,'partial'),
('ameba','code_assistant','コーディング支援',false,'notYet'),
('ameba','document_management','ドキュメント管理',true,'partial'),
('ameba','collaboration','コラボレーション',false,'notYet'),
('hatena','notes','ノート・メモ',true,'done'),
('hatena','task_management','タスク管理',false,'done'),
('hatena','calendar','カレンダー',false,'notYet'),
('hatena','finance_tracking','家計・資産管理',false,'done'),
('hatena','ai_assistant','AIアシスタント',false,'done'),
('hatena','messaging','メッセージ',false,'done'),
('hatena','social_sharing','SNS・ソーシャル共有',true,'partial'),
('hatena','code_assistant','コーディング支援',false,'notYet'),
('hatena','document_management','ドキュメント管理',true,'partial'),
('hatena','collaboration','コラボレーション',false,'notYet'),
('niconico','notes','ノート・メモ',false,'done'),
('niconico','task_management','タスク管理',false,'done'),
('niconico','calendar','カレンダー',false,'notYet'),
('niconico','finance_tracking','家計・資産管理',false,'done'),
('niconico','ai_assistant','AIアシスタント',true,'done'),
('niconico','messaging','メッセージ',true,'done'),
('niconico','social_sharing','SNS・ソーシャル共有',true,'partial'),
('niconico','code_assistant','コーディング支援',false,'notYet'),
('niconico','document_management','ドキュメント管理',false,'partial'),
('niconico','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- e-commerce (8社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('base','notes','ノート・メモ',false,'done'),
('base','task_management','タスク管理',false,'done'),
('base','calendar','カレンダー',false,'notYet'),
('base','finance_tracking','家計・資産管理',true,'done'),
('base','ai_assistant','AIアシスタント',true,'done'),
('base','messaging','メッセージ',false,'done'),
('base','social_sharing','SNS・ソーシャル共有',true,'partial'),
('base','code_assistant','コーディング支援',false,'notYet'),
('base','document_management','ドキュメント管理',true,'partial'),
('base','collaboration','コラボレーション',false,'notYet'),
('ecforce','notes','ノート・メモ',false,'done'),
('ecforce','task_management','タスク管理',true,'done'),
('ecforce','calendar','カレンダー',false,'notYet'),
('ecforce','finance_tracking','家計・資産管理',true,'done'),
('ecforce','ai_assistant','AIアシスタント',true,'done'),
('ecforce','messaging','メッセージ',false,'done'),
('ecforce','social_sharing','SNS・ソーシャル共有',false,'partial'),
('ecforce','code_assistant','コーディング支援',false,'notYet'),
('ecforce','document_management','ドキュメント管理',true,'partial'),
('ecforce','collaboration','コラボレーション',true,'notYet'),
('mercari','notes','ノート・メモ',false,'done'),
('mercari','task_management','タスク管理',false,'done'),
('mercari','calendar','カレンダー',false,'notYet'),
('mercari','finance_tracking','家計・資産管理',true,'done'),
('mercari','ai_assistant','AIアシスタント',true,'done'),
('mercari','messaging','メッセージ',true,'done'),
('mercari','social_sharing','SNS・ソーシャル共有',true,'partial'),
('mercari','code_assistant','コーディング支援',false,'notYet'),
('mercari','document_management','ドキュメント管理',false,'partial'),
('mercari','collaboration','コラボレーション',false,'notYet'),
('poshmark','notes','ノート・メモ',false,'done'),
('poshmark','task_management','タスク管理',false,'done'),
('poshmark','calendar','カレンダー',false,'notYet'),
('poshmark','finance_tracking','家計・資産管理',true,'done'),
('poshmark','ai_assistant','AIアシスタント',true,'done'),
('poshmark','messaging','メッセージ',true,'done'),
('poshmark','social_sharing','SNS・ソーシャル共有',true,'partial'),
('poshmark','code_assistant','コーディング支援',false,'notYet'),
('poshmark','document_management','ドキュメント管理',false,'partial'),
('poshmark','collaboration','コラボレーション',false,'notYet'),
('rakuten','notes','ノート・メモ',false,'done'),
('rakuten','task_management','タスク管理',false,'done'),
('rakuten','calendar','カレンダー',false,'notYet'),
('rakuten','finance_tracking','家計・資産管理',true,'done'),
('rakuten','ai_assistant','AIアシスタント',true,'done'),
('rakuten','messaging','メッセージ',true,'done'),
('rakuten','social_sharing','SNS・ソーシャル共有',true,'partial'),
('rakuten','code_assistant','コーディング支援',false,'notYet'),
('rakuten','document_management','ドキュメント管理',false,'partial'),
('rakuten','collaboration','コラボレーション',false,'notYet'),
('shopify','notes','ノート・メモ',false,'done'),
('shopify','task_management','タスク管理',true,'done'),
('shopify','calendar','カレンダー',false,'notYet'),
('shopify','finance_tracking','家計・資産管理',true,'done'),
('shopify','ai_assistant','AIアシスタント',true,'done'),
('shopify','messaging','メッセージ',false,'done'),
('shopify','social_sharing','SNS・ソーシャル共有',true,'partial'),
('shopify','code_assistant','コーディング支援',true,'notYet'),
('shopify','document_management','ドキュメント管理',true,'partial'),
('shopify','collaboration','コラボレーション',true,'notYet'),
('stores-jp','notes','ノート・メモ',false,'done'),
('stores-jp','task_management','タスク管理',false,'done'),
('stores-jp','calendar','カレンダー',false,'notYet'),
('stores-jp','finance_tracking','家計・資産管理',true,'done'),
('stores-jp','ai_assistant','AIアシスタント',true,'done'),
('stores-jp','messaging','メッセージ',false,'done'),
('stores-jp','social_sharing','SNS・ソーシャル共有',true,'partial'),
('stores-jp','code_assistant','コーディング支援',false,'notYet'),
('stores-jp','document_management','ドキュメント管理',false,'partial'),
('stores-jp','collaboration','コラボレーション',false,'notYet'),
('tiktok-shop','notes','ノート・メモ',false,'done'),
('tiktok-shop','task_management','タスク管理',false,'done'),
('tiktok-shop','calendar','カレンダー',false,'notYet'),
('tiktok-shop','finance_tracking','家計・資産管理',true,'done'),
('tiktok-shop','ai_assistant','AIアシスタント',true,'done'),
('tiktok-shop','messaging','メッセージ',true,'done'),
('tiktok-shop','social_sharing','SNS・ソーシャル共有',true,'partial'),
('tiktok-shop','code_assistant','コーディング支援',false,'notYet'),
('tiktok-shop','document_management','ドキュメント管理',false,'partial'),
('tiktok-shop','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- education (3社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('progate','notes','ノート・メモ',false,'done'),
('progate','task_management','タスク管理',true,'done'),
('progate','calendar','カレンダー',false,'notYet'),
('progate','finance_tracking','家計・資産管理',false,'done'),
('progate','ai_assistant','AIアシスタント',true,'done'),
('progate','messaging','メッセージ',false,'done'),
('progate','social_sharing','SNS・ソーシャル共有',true,'partial'),
('progate','code_assistant','コーディング支援',true,'notYet'),
('progate','document_management','ドキュメント管理',false,'partial'),
('progate','collaboration','コラボレーション',false,'notYet'),
('schoo','notes','ノート・メモ',true,'done'),
('schoo','task_management','タスク管理',false,'done'),
('schoo','calendar','カレンダー',true,'notYet'),
('schoo','finance_tracking','家計・資産管理',false,'done'),
('schoo','ai_assistant','AIアシスタント',true,'done'),
('schoo','messaging','メッセージ',false,'done'),
('schoo','social_sharing','SNS・ソーシャル共有',true,'partial'),
('schoo','code_assistant','コーディング支援',false,'notYet'),
('schoo','document_management','ドキュメント管理',false,'partial'),
('schoo','collaboration','コラボレーション',false,'notYet'),
('udemy','notes','ノート・メモ',true,'done'),
('udemy','task_management','タスク管理',false,'done'),
('udemy','calendar','カレンダー',false,'notYet'),
('udemy','finance_tracking','家計・資産管理',false,'done'),
('udemy','ai_assistant','AIアシスタント',true,'done'),
('udemy','messaging','メッセージ',false,'done'),
('udemy','social_sharing','SNS・ソーシャル共有',true,'partial'),
('udemy','code_assistant','コーディング支援',true,'notYet'),
('udemy','document_management','ドキュメント管理',false,'partial'),
('udemy','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- hr-tech (1社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('hrmos','notes','ノート・メモ',true,'done'),
('hrmos','task_management','タスク管理',true,'done'),
('hrmos','calendar','カレンダー',true,'notYet'),
('hrmos','finance_tracking','家計・資産管理',true,'done'),
('hrmos','ai_assistant','AIアシスタント',true,'done'),
('hrmos','messaging','メッセージ',true,'done'),
('hrmos','social_sharing','SNS・ソーシャル共有',false,'partial'),
('hrmos','code_assistant','コーディング支援',false,'notYet'),
('hrmos','document_management','ドキュメント管理',true,'partial'),
('hrmos','collaboration','コラボレーション',true,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- legal-tech (3社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('cloudsign','notes','ノート・メモ',false,'done'),
('cloudsign','task_management','タスク管理',true,'done'),
('cloudsign','calendar','カレンダー',false,'notYet'),
('cloudsign','finance_tracking','家計・資産管理',false,'done'),
('cloudsign','ai_assistant','AIアシスタント',true,'done'),
('cloudsign','messaging','メッセージ',true,'done'),
('cloudsign','social_sharing','SNS・ソーシャル共有',false,'partial'),
('cloudsign','code_assistant','コーディング支援',false,'notYet'),
('cloudsign','document_management','ドキュメント管理',true,'partial'),
('cloudsign','collaboration','コラボレーション',true,'notYet'),
('docusign','notes','ノート・メモ',false,'done'),
('docusign','task_management','タスク管理',true,'done'),
('docusign','calendar','カレンダー',false,'notYet'),
('docusign','finance_tracking','家計・資産管理',false,'done'),
('docusign','ai_assistant','AIアシスタント',true,'done'),
('docusign','messaging','メッセージ',false,'done'),
('docusign','social_sharing','SNS・ソーシャル共有',false,'partial'),
('docusign','code_assistant','コーディング支援',false,'notYet'),
('docusign','document_management','ドキュメント管理',true,'partial'),
('docusign','collaboration','コラボレーション',true,'notYet'),
('harvey-ai','notes','ノート・メモ',true,'done'),
('harvey-ai','task_management','タスク管理',true,'done'),
('harvey-ai','calendar','カレンダー',false,'notYet'),
('harvey-ai','finance_tracking','家計・資産管理',false,'done'),
('harvey-ai','ai_assistant','AIアシスタント',true,'done'),
('harvey-ai','messaging','メッセージ',true,'done'),
('harvey-ai','social_sharing','SNS・ソーシャル共有',false,'partial'),
('harvey-ai','code_assistant','コーディング支援',false,'notYet'),
('harvey-ai','document_management','ドキュメント管理',true,'partial'),
('harvey-ai','collaboration','コラボレーション',true,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- logistics (2社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('sagawa-express','notes','ノート・メモ',false,'done'),
('sagawa-express','task_management','タスク管理',true,'done'),
('sagawa-express','calendar','カレンダー',false,'notYet'),
('sagawa-express','finance_tracking','家計・資産管理',true,'done'),
('sagawa-express','ai_assistant','AIアシスタント',true,'done'),
('sagawa-express','messaging','メッセージ',false,'done'),
('sagawa-express','social_sharing','SNS・ソーシャル共有',false,'partial'),
('sagawa-express','code_assistant','コーディング支援',false,'notYet'),
('sagawa-express','document_management','ドキュメント管理',true,'partial'),
('sagawa-express','collaboration','コラボレーション',false,'notYet'),
('yamato-transport','notes','ノート・メモ',false,'done'),
('yamato-transport','task_management','タスク管理',true,'done'),
('yamato-transport','calendar','カレンダー',false,'notYet'),
('yamato-transport','finance_tracking','家計・資産管理',true,'done'),
('yamato-transport','ai_assistant','AIアシスタント',true,'done'),
('yamato-transport','messaging','メッセージ',false,'done'),
('yamato-transport','social_sharing','SNS・ソーシャル共有',false,'partial'),
('yamato-transport','code_assistant','コーディング支援',false,'notYet'),
('yamato-transport','document_management','ドキュメント管理',true,'partial'),
('yamato-transport','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- telecom JP (3社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('kddi-au','notes','ノート・メモ',false,'done'),
('kddi-au','task_management','タスク管理',false,'done'),
('kddi-au','calendar','カレンダー',true,'notYet'),
('kddi-au','finance_tracking','家計・資産管理',true,'done'),
('kddi-au','ai_assistant','AIアシスタント',true,'done'),
('kddi-au','messaging','メッセージ',true,'done'),
('kddi-au','social_sharing','SNS・ソーシャル共有',false,'partial'),
('kddi-au','code_assistant','コーディング支援',false,'notYet'),
('kddi-au','document_management','ドキュメント管理',false,'partial'),
('kddi-au','collaboration','コラボレーション',false,'notYet'),
('ntt-docomo','notes','ノート・メモ',false,'done'),
('ntt-docomo','task_management','タスク管理',false,'done'),
('ntt-docomo','calendar','カレンダー',true,'notYet'),
('ntt-docomo','finance_tracking','家計・資産管理',true,'done'),
('ntt-docomo','ai_assistant','AIアシスタント',true,'done'),
('ntt-docomo','messaging','メッセージ',true,'done'),
('ntt-docomo','social_sharing','SNS・ソーシャル共有',false,'partial'),
('ntt-docomo','code_assistant','コーディング支援',false,'notYet'),
('ntt-docomo','document_management','ドキュメント管理',false,'partial'),
('ntt-docomo','collaboration','コラボレーション',false,'notYet'),
('softbank-telecom','notes','ノート・メモ',false,'done'),
('softbank-telecom','task_management','タスク管理',false,'done'),
('softbank-telecom','calendar','カレンダー',true,'notYet'),
('softbank-telecom','finance_tracking','家計・資産管理',true,'done'),
('softbank-telecom','ai_assistant','AIアシスタント',true,'done'),
('softbank-telecom','messaging','メッセージ',true,'done'),
('softbank-telecom','social_sharing','SNS・ソーシャル共有',false,'partial'),
('softbank-telecom','code_assistant','コーディング支援',false,'notYet'),
('softbank-telecom','document_management','ドキュメント管理',false,'partial'),
('softbank-telecom','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- advertising (3社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('criteo','notes','ノート・メモ',false,'done'),
('criteo','task_management','タスク管理',false,'done'),
('criteo','calendar','カレンダー',false,'notYet'),
('criteo','finance_tracking','家計・資産管理',true,'done'),
('criteo','ai_assistant','AIアシスタント',true,'done'),
('criteo','messaging','メッセージ',false,'done'),
('criteo','social_sharing','SNS・ソーシャル共有',false,'partial'),
('criteo','code_assistant','コーディング支援',false,'notYet'),
('criteo','document_management','ドキュメント管理',true,'partial'),
('criteo','collaboration','コラボレーション',false,'notYet'),
('google-ads','notes','ノート・メモ',false,'done'),
('google-ads','task_management','タスク管理',false,'done'),
('google-ads','calendar','カレンダー',false,'notYet'),
('google-ads','finance_tracking','家計・資産管理',true,'done'),
('google-ads','ai_assistant','AIアシスタント',true,'done'),
('google-ads','messaging','メッセージ',false,'done'),
('google-ads','social_sharing','SNS・ソーシャル共有',false,'partial'),
('google-ads','code_assistant','コーディング支援',false,'notYet'),
('google-ads','document_management','ドキュメント管理',true,'partial'),
('google-ads','collaboration','コラボレーション',false,'notYet'),
('meta-ads','notes','ノート・メモ',false,'done'),
('meta-ads','task_management','タスク管理',false,'done'),
('meta-ads','calendar','カレンダー',false,'notYet'),
('meta-ads','finance_tracking','家計・資産管理',true,'done'),
('meta-ads','ai_assistant','AIアシスタント',true,'done'),
('meta-ads','messaging','メッセージ',false,'done'),
('meta-ads','social_sharing','SNS・ソーシャル共有',true,'partial'),
('meta-ads','code_assistant','コーディング支援',false,'notYet'),
('meta-ads','document_management','ドキュメント管理',true,'partial'),
('meta-ads','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- gov-tech (2社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('digi-smac','notes','ノート・メモ',true,'done'),
('digi-smac','task_management','タスク管理',true,'done'),
('digi-smac','calendar','カレンダー',true,'notYet'),
('digi-smac','finance_tracking','家計・資産管理',false,'done'),
('digi-smac','ai_assistant','AIアシスタント',true,'done'),
('digi-smac','messaging','メッセージ',true,'done'),
('digi-smac','social_sharing','SNS・ソーシャル共有',false,'partial'),
('digi-smac','code_assistant','コーディング支援',false,'notYet'),
('digi-smac','document_management','ドキュメント管理',true,'partial'),
('digi-smac','collaboration','コラボレーション',true,'notYet'),
('graffer','notes','ノート・メモ',true,'done'),
('graffer','task_management','タスク管理',true,'done'),
('graffer','calendar','カレンダー',false,'notYet'),
('graffer','finance_tracking','家計・資産管理',false,'done'),
('graffer','ai_assistant','AIアシスタント',true,'done'),
('graffer','messaging','メッセージ',true,'done'),
('graffer','social_sharing','SNS・ソーシャル共有',false,'partial'),
('graffer','code_assistant','コーディング支援',false,'notYet'),
('graffer','document_management','ドキュメント管理',true,'partial'),
('graffer','collaboration','コラボレーション',true,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- mobility (3社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('go-taxi','notes','ノート・メモ',false,'done'),
('go-taxi','task_management','タスク管理',false,'done'),
('go-taxi','calendar','カレンダー',true,'notYet'),
('go-taxi','finance_tracking','家計・資産管理',true,'done'),
('go-taxi','ai_assistant','AIアシスタント',true,'done'),
('go-taxi','messaging','メッセージ',true,'done'),
('go-taxi','social_sharing','SNS・ソーシャル共有',false,'partial'),
('go-taxi','code_assistant','コーディング支援',false,'notYet'),
('go-taxi','document_management','ドキュメント管理',false,'partial'),
('go-taxi','collaboration','コラボレーション',false,'notYet'),
('luup-micromobility','notes','ノート・メモ',false,'done'),
('luup-micromobility','task_management','タスク管理',false,'done'),
('luup-micromobility','calendar','カレンダー',false,'notYet'),
('luup-micromobility','finance_tracking','家計・資産管理',true,'done'),
('luup-micromobility','ai_assistant','AIアシスタント',true,'done'),
('luup-micromobility','messaging','メッセージ',false,'done'),
('luup-micromobility','social_sharing','SNS・ソーシャル共有',false,'partial'),
('luup-micromobility','code_assistant','コーディング支援',false,'notYet'),
('luup-micromobility','document_management','ドキュメント管理',false,'partial'),
('luup-micromobility','collaboration','コラボレーション',false,'notYet'),
('toyota-connected','notes','ノート・メモ',false,'done'),
('toyota-connected','task_management','タスク管理',false,'done'),
('toyota-connected','calendar','カレンダー',true,'notYet'),
('toyota-connected','finance_tracking','家計・資産管理',false,'done'),
('toyota-connected','ai_assistant','AIアシスタント',true,'done'),
('toyota-connected','messaging','メッセージ',true,'done'),
('toyota-connected','social_sharing','SNS・ソーシャル共有',false,'partial'),
('toyota-connected','code_assistant','コーディング支援',false,'notYet'),
('toyota-connected','document_management','ドキュメント管理',false,'partial'),
('toyota-connected','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- real-estate (2社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('itandi','notes','ノート・メモ',true,'done'),
('itandi','task_management','タスク管理',true,'done'),
('itandi','calendar','カレンダー',true,'notYet'),
('itandi','finance_tracking','家計・資産管理',false,'done'),
('itandi','ai_assistant','AIアシスタント',true,'done'),
('itandi','messaging','メッセージ',true,'done'),
('itandi','social_sharing','SNS・ソーシャル共有',false,'partial'),
('itandi','code_assistant','コーディング支援',false,'notYet'),
('itandi','document_management','ドキュメント管理',true,'partial'),
('itandi','collaboration','コラボレーション',true,'notYet'),
('suumo','notes','ノート・メモ',false,'done'),
('suumo','task_management','タスク管理',false,'done'),
('suumo','calendar','カレンダー',false,'notYet'),
('suumo','finance_tracking','家計・資産管理',false,'done'),
('suumo','ai_assistant','AIアシスタント',true,'done'),
('suumo','messaging','メッセージ',true,'done'),
('suumo','social_sharing','SNS・ソーシャル共有',false,'partial'),
('suumo','code_assistant','コーディング支援',false,'notYet'),
('suumo','document_management','ドキュメント管理',false,'partial'),
('suumo','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- travel (2社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('ikyu','notes','ノート・メモ',false,'done'),
('ikyu','task_management','タスク管理',false,'done'),
('ikyu','calendar','カレンダー',true,'notYet'),
('ikyu','finance_tracking','家計・資産管理',false,'done'),
('ikyu','ai_assistant','AIアシスタント',true,'done'),
('ikyu','messaging','メッセージ',false,'done'),
('ikyu','social_sharing','SNS・ソーシャル共有',true,'partial'),
('ikyu','code_assistant','コーディング支援',false,'notYet'),
('ikyu','document_management','ドキュメント管理',false,'partial'),
('ikyu','collaboration','コラボレーション',false,'notYet'),
('jalan','notes','ノート・メモ',false,'done'),
('jalan','task_management','タスク管理',false,'done'),
('jalan','calendar','カレンダー',true,'notYet'),
('jalan','finance_tracking','家計・資産管理',false,'done'),
('jalan','ai_assistant','AIアシスタント',true,'done'),
('jalan','messaging','メッセージ',false,'done'),
('jalan','social_sharing','SNS・ソーシャル共有',true,'partial'),
('jalan','code_assistant','コーディング支援',false,'notYet'),
('jalan','document_management','ドキュメント管理',false,'partial'),
('jalan','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

-- food-delivery (2社)
INSERT INTO public.competitor_features (competitor_id, feature_key, feature_name_ja, has_feature, jibun_status) VALUES
('tabelog','notes','ノート・メモ',true,'done'),
('tabelog','task_management','タスク管理',false,'done'),
('tabelog','calendar','カレンダー',true,'notYet'),
('tabelog','finance_tracking','家計・資産管理',false,'done'),
('tabelog','ai_assistant','AIアシスタント',true,'done'),
('tabelog','messaging','メッセージ',false,'done'),
('tabelog','social_sharing','SNS・ソーシャル共有',true,'partial'),
('tabelog','code_assistant','コーディング支援',false,'notYet'),
('tabelog','document_management','ドキュメント管理',false,'partial'),
('tabelog','collaboration','コラボレーション',false,'notYet'),
('ubereats-japan','notes','ノート・メモ',false,'done'),
('ubereats-japan','task_management','タスク管理',false,'done'),
('ubereats-japan','calendar','カレンダー',false,'notYet'),
('ubereats-japan','finance_tracking','家計・資産管理',true,'done'),
('ubereats-japan','ai_assistant','AIアシスタント',true,'done'),
('ubereats-japan','messaging','メッセージ',true,'done'),
('ubereats-japan','social_sharing','SNS・ソーシャル共有',false,'partial'),
('ubereats-japan','code_assistant','コーディング支援',false,'notYet'),
('ubereats-japan','document_management','ドキュメント管理',false,'partial'),
('ubereats-japan','collaboration','コラボレーション',false,'notYet')
ON CONFLICT (competitor_id, feature_key) DO UPDATE SET
  has_feature = EXCLUDED.has_feature,
  feature_name_ja = EXCLUDED.feature_name_ja,
  jibun_status = EXCLUDED.jibun_status,
  updated_at = now();

INSERT INTO public.development_achievements (title, description, completed_at)
VALUES (
  'competitor_features Phase 2 完了: 172社×10機能 1720行',
  'Batch 4/4 (entertainment/health/hr-attendance/media/e-commerce/education/legal-tech/logistics/telecom/advertising/gov-tech/mobility/real-estate/travel/food-delivery 58社) seed完了。Phase 2全4バッチで21→172社 feature data拡充完了。',
  '2026-04-26'
)
ON CONFLICT DO NOTHING;
