-- User-editable proposals produced by domain-specific micro mentors.

create table if not exists public.micro_mentor_proposals (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  mentor_id uuid not null references public.agents(id) on delete cascade,
  focus text not null check (char_length(focus) between 1 and 1000),
  proposal_type text not null check (proposal_type in ('task', 'schedule')),
  title text not null check (char_length(title) between 1 and 120),
  description text not null check (char_length(description) between 1 and 2000),
  rationale text not null check (char_length(rationale) between 1 and 1000),
  scheduled_for timestamptz,
  status text not null default 'proposed'
    check (status in ('proposed', 'accepted', 'rejected')),
  original_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint micro_mentor_proposals_task_has_no_schedule
    check (proposal_type = 'schedule' or scheduled_for is null)
);

create index if not exists idx_micro_mentor_proposals_user_created
  on public.micro_mentor_proposals(user_id, created_at desc);

create index if not exists idx_micro_mentor_proposals_mentor_status
  on public.micro_mentor_proposals(mentor_id, status, created_at desc);

drop trigger if exists trg_micro_mentor_proposals_updated_at
  on public.micro_mentor_proposals;
create trigger trg_micro_mentor_proposals_updated_at
  before update on public.micro_mentor_proposals
  for each row execute function public.set_agent_org_updated_at();

alter table public.micro_mentor_proposals enable row level security;

revoke all on table public.micro_mentor_proposals from anon;
grant select, insert, update, delete
  on table public.micro_mentor_proposals to authenticated;

drop policy if exists micro_mentor_proposals_select_own
  on public.micro_mentor_proposals;
create policy micro_mentor_proposals_select_own
  on public.micro_mentor_proposals
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

drop policy if exists micro_mentor_proposals_insert_own
  on public.micro_mentor_proposals;
create policy micro_mentor_proposals_insert_own
  on public.micro_mentor_proposals
  for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1
      from public.agents
      where agents.id = mentor_id
        and agents.user_id = (select auth.uid())
        and agents.metadata ->> 'profile_type' = 'micro_mentor'
    )
  );

drop policy if exists micro_mentor_proposals_update_own
  on public.micro_mentor_proposals;
create policy micro_mentor_proposals_update_own
  on public.micro_mentor_proposals
  for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1
      from public.agents
      where agents.id = mentor_id
        and agents.user_id = (select auth.uid())
        and agents.metadata ->> 'profile_type' = 'micro_mentor'
    )
  );

drop policy if exists micro_mentor_proposals_delete_own
  on public.micro_mentor_proposals;
create policy micro_mentor_proposals_delete_own
  on public.micro_mentor_proposals
  for delete
  to authenticated
  using ((select auth.uid()) = user_id);

comment on table public.micro_mentor_proposals is
  'Editable task and schedule proposals generated by user-configured micro mentors';
