import {test,expect,type Page} from '@playwright/test';
async function screenshot(page: Page, path: string) {
  // Expand only the test harness height so the full iframe document is visible.
  await page.locator('iframe').evaluate((element) => {
    const frame = element as HTMLIFrameElement;
    frame.style.height = `${frame.contentDocument!.documentElement.scrollHeight}px`;
    frame.contentWindow!.scrollTo(0, 0);
  });
  await page.screenshot({ path, fullPage: true });
}
test.beforeEach(async({page})=>{await page.route("**/test/e2e/jev_mario_harness.html",route=>route.fulfill({contentType:"text/html",body:"<!doctype html><html lang=\"ja\"><meta charset=\"utf-8\"><meta name=\"viewport\" content=\"width=device-width,initial-scale=1\"><title>TEST FIXTURE \u2014 simulated Jev bridge</title>\n<style>body{margin:0}iframe{border:0;width:100%;height:100vh}</style>\n<iframe title=\"Jev lab test fixture\" src=\"/labs/jev-mario/index.html\"></iframe>\n<script>\n// Test only. Not copied into web/ or production artifacts. No API credentials.\nlet calls = 0;\nwindow.addEventListener('message', e => {\n  const frame = document.querySelector('iframe');\n  if (e.source !== frame.contentWindow || e.origin !== location.origin) return;\n  if (e.data?.type === 'jev-mario-hello') frame.contentWindow.postMessage({ type:'jev-mario-ready' },location.origin);\n  if (e.data?.type === 'jev-mario-request') {\n    calls++;\n    const error = new URL(location.href).searchParams.has('error') && calls === 1;\n    const params = new URL(location.href).searchParams;\n    const delay = params.has('slow') ? 1000 : params.has('latency') ? 1000 : 10;\n    setTimeout(() => frame.contentWindow.postMessage({type:'jev-mario-response',id:e.data.id,\n      ...(error ? {error:'API\u5229\u7528\u4e0a\u9650\u306b\u9054\u3057\u307e\u3057\u305f\u3002\u6642\u9593\u3092\u304a\u3044\u3066\u518d\u8a66\u884c\u3057\u3066\u304f\u3060\u3055\u3044\u3002'} :\n        {result:{choice:'right',confidence:.9,probabilities:{right:1},upstream_http_ms:5,model:'test-fixture'}})\n    }, location.origin),delay);\n  }\n});\n</script></html>\n"}));});
test('8-4 complete real worker castle collects items and clears with normal hazards',async({page},info)=>{
 test.skip(info.project.name==='mobile','The complete run uses desktop; mobile entrance and overhang recovery are covered separately.');test.setTimeout(180000);
 await page.goto('/test/e2e/jev_mario_harness.html');const lab=page.frameLocator('iframe'),frame=page.frames().find(f=>f.parentFrame())!;await lab.locator('#stage').selectOption('32');
 await frame.evaluate(async()=>{const {World11}=await import('/labs/jev-mario/world11.mjs?v=student-1');const {StudentSession}=await import('/labs/jev-mario/student-session.mjs?v=student-1');const tick=StudentSession.prototype.tick,step=World11.prototype.step;(window as any).courseTrace=[];(window as any).courseClear=null;(window as any).courseTotals={mushroom:0,flower:0,life:0,star:0};let previous={mushroom:0,flower:0,life:0,star:0},totalFrames=0;StudentSession.prototype.tick=function(world){(window as any).courseWorld=world;return tick.call(this,world);};World11.prototype.step=function(){step.call(this);if(this!==(window as any).courseWorld)return;totalFrames++;for(const kind of Object.keys(previous)){(window as any).courseTotals[kind]+=Math.max(0,this.pickups[kind]-previous[kind]);previous[kind]=this.pickups[kind];}if(this.frames%60===0)(window as any).courseTrace.push({frame:this.frames,x:this.p.x,y:this.p.y,room:this.room,phase:this.phase,lives:this.lives,pickups:{...this.pickups},input:{...this.input},power:this.power});if(this.stage===32&&this.phase==='won')(window as any).courseClear={frames:this.frames,totalFrames,x:this.p.x,lives:this.lives,deaths:this.deaths,pickups:{...(window as any).courseTotals},finalAttemptPickups:{...this.pickups},visited:[...this.visitedPipes]};};});
 await lab.locator('#play-student').click();await expect(lab.locator('#status')).toContainText('LightGBM＋探索でプレイ中',{timeout:15000});
 try{await expect.poll(()=>frame.evaluate(()=>(window as any).courseClear),{timeout:160000}).toBeTruthy();const result=await frame.evaluate(()=>(window as any).courseClear);expect(result.pickups.mushroom).toBeGreaterThan(0);}
 finally{await lab.locator('#stop').click();await(await import('node:fs/promises')).writeFile(info.outputPath('world84-complete-worker.json'),JSON.stringify(await frame.evaluate(()=>({clear:(window as any).courseClear,trace:(window as any).courseTrace}))));await screenshot(page,info.outputPath('world84-complete-worker.png'));}
});
